ab \exclamdown ¡ 
ab \sterling £ 
ab \yen ¥ 
ab \brokenbar ¦ 
ab \S § 
ab \copyright © 
ab \copyright © 
ab \ordfeminine ª 
ab \neg ¬ 
ab \circledR ® 
ab \registered ® 
ab \highminus ¯ 
ab \degree ° 
ab \pm ± 
ab \^2 ² 
ab \^3 ³ 
ab \P ¶ 
ab \cdotp · 
ab \^1 ¹ 
ab \ordmasculine º 
ab \1/4 ¼ 
ab \1/2 ½ 
ab \3/4 ¾ 
ab \questiondown ¿ 
ab \AA Å 
ab \AE Æ 
ab \DH Ð 
ab \times × 
ab \O Ø 
ab \TH Þ 
ab \ss ß 
ab \aa å 
ab \ae æ 
ab \eth ð 
ab \dh ð 
ab \div ÷ 
ab \o ø 
ab \th þ 
ab \DJ Đ 
ab \dj đ 
ab \hbar ħ 
ab \imath ı 
ab \L Ł 
ab \l ł 
ab \NG Ŋ 
ab \ng ŋ 
ab \OE Œ 
ab \oe œ 
ab \hvlig ƕ 
ab \nrleg ƞ 
ab \Zbar Ƶ 
ab \doublepipe ǂ 
ab \jmath ȷ 
ab \trna ɐ 
ab \trnsa ɒ 
ab \openo ɔ 
ab \rtld ɖ 
ab \schwa ə 
ab \pgamma ɣ 
ab \pbgam ɤ 
ab \trnh ɥ 
ab \btdl ɬ 
ab \rtll ɭ 
ab \trnm ɯ 
ab \trnmlr ɰ 
ab \ltlmr ɱ 
ab \ltln ɲ 
ab \rtln ɳ 
ab \clomeg ɷ 
ab \ltphi ɸ 
ab \trnr ɹ 
ab \trnrl ɺ 
ab \rttrnr ɻ 
ab \rl ɼ 
ab \rtlr ɽ 
ab \fhr ɾ 
ab \rtls ʂ 
ab \esh ʃ 
ab \trnt ʇ 
ab \rtlt ʈ 
ab \pupsil ʊ 
ab \pscrv ʋ 
ab \invv ʌ 
ab \invw ʍ 
ab \trny ʎ 
ab \rtlz ʐ 
ab \yogh ʒ 
ab \glst ʔ 
ab \reglst ʕ 
ab \inglst ʖ 
ab \turnk ʞ 
ab \dyogh ʤ 
ab \tesh ʧ 
ab \^h ʰ 
ab \^j ʲ 
ab \^r ʳ 
ab \^w ʷ 
ab \^y ʸ 
ab \rasp ʼ 
ab \verts ˈ 
ab \verti ˌ 
ab \lmrk ː 
ab \hlmrk ˑ 
ab \sbrhr ˒ 
ab \sblhr ˓ 
ab \rais ˔ 
ab \low ˕ 
ab \u ˘ 
ab \tildelow ˜ 
ab \^l ˡ 
ab \^s ˢ 
ab \^x ˣ 
ab \grave '̀ 
ab \acute '́ 
ab \hat '̂ 
ab \tilde '̃ 
ab \bar '̄ 
ab \overbar '̅ 
ab \breve '̆ 
ab \dot '̇ 
ab \ddot '̈ 
ab \ovhook '̉ 
ab \ocirc '̊ 
ab \H '̋ 
ab \check '̌ 
ab \candra '̐ 
ab \oturnedcomma '̒ 
ab \ocommatopright '̕ 
ab \droang '̚ 
ab \palh '̡ 
ab \rh '̢ 
ab \c '̧ 
ab \k '̨ 
ab \sbbrg '̪ 
ab \wideutilde '̰ 
ab \underbar '̲ 
ab \strike '̶ 
ab \sout '̶ 
ab \not '̸ 
ab \underleftrightarrow '͍ 
ab \Alpha Α 
ab \Beta Β 
ab \Gamma Γ 
ab \Delta Δ 
ab \Epsilon Ε 
ab \Zeta Ζ 
ab \Eta Η 
ab \Theta Θ 
ab \Iota Ι 
ab \Kappa Κ 
ab \Lambda Λ 
ab \upMu Μ 
ab \upNu Ν 
ab \Xi Ξ 
ab \upOmicron Ο 
ab \Pi Π 
ab \Rho Ρ 
ab \Sigma Σ 
ab \Tau Τ 
ab \Upsilon Υ 
ab \Phi Φ 
ab \Chi Χ 
ab \Psi Ψ 
ab \Omega Ω 
ab \alpha α 
ab \beta β 
ab \gamma γ 
ab \delta δ 
ab \upepsilon ε 
ab \varepsilon ε 
ab \zeta ζ 
ab \eta η 
ab \theta θ 
ab \iota ι 
ab \kappa κ 
ab \lambda λ 
ab \mu μ 
ab \nu ν 
ab \xi ξ 
ab \upomicron ο 
ab \pi π 
ab \rho ρ 
ab \varsigma ς 
ab \sigma σ 
ab \tau τ 
ab \upsilon υ 
ab \varphi φ 
ab \chi χ 
ab \psi ψ 
ab \omega ω 
ab \upvarbeta ϐ 
ab \vartheta ϑ 
ab \phi ϕ 
ab \varpi ϖ 
ab \upoldKoppa Ϙ 
ab \upoldkoppa ϙ 
ab \Stigma Ϛ 
ab \upstigma ϛ 
ab \Digamma Ϝ 
ab \digamma ϝ 
ab \Koppa Ϟ 
ab \upkoppa ϟ 
ab \Sampi Ϡ 
ab \upsampi ϡ 
ab \varkappa ϰ 
ab \varrho ϱ 
ab \varTheta ϴ 
ab \epsilon ϵ 
ab \backepsilon ϶ 
ab \^A ᴬ 
ab \^B ᴮ 
ab \^D ᴰ 
ab \^E ᴱ 
ab \^G ᴳ 
ab \^H ᴴ 
ab \^I ᴵ 
ab \^J ᴶ 
ab \^K ᴷ 
ab \^L ᴸ 
ab \^M ᴹ 
ab \^N ᴺ 
ab \^O ᴼ 
ab \^P ᴾ 
ab \^R ᴿ 
ab \^T ᵀ 
ab \^U ᵁ 
ab \^W ᵂ 
ab \^a ᵃ 
ab \^alpha ᵅ 
ab \^b ᵇ 
ab \^d ᵈ 
ab \^e ᵉ 
ab \^epsilon ᵋ 
ab \^g ᵍ 
ab \^k ᵏ 
ab \^m ᵐ 
ab \^o ᵒ 
ab \^p ᵖ 
ab \^t ᵗ 
ab \^u ᵘ 
ab \^v ᵛ 
ab \^beta ᵝ 
ab \^gamma ᵞ 
ab \^delta ᵟ 
ab \^phi ᵠ 
ab \^chi ᵡ 
ab \_i ᵢ 
ab \_r ᵣ 
ab \_u ᵤ 
ab \_v ᵥ 
ab \_beta ᵦ 
ab \_gamma ᵧ 
ab \_rho ᵨ 
ab \_phi ᵩ 
ab \_chi ᵪ 
ab \^c ᶜ 
ab \^f ᶠ 
ab \^iota ᶥ 
ab \^Phi ᶲ 
ab \^z ᶻ 
ab \^theta ᶿ 
ab \enspace   
ab \quad   
ab \thickspace   
ab \thinspace   
ab \hspace   
ab \endash – 
ab \emdash — 
ab \Vert ‖ 
ab \lq ‘ 
ab \rq ’ 
ab \reapos ‛ 
ab \quotedblleft “ 
ab \quotedblright ” 
ab \dagger † 
ab \ddagger ‡ 
ab \bullet • 
ab \dots … 
ab \ldots … 
ab \perthousand ‰ 
ab \pertenthousand ‱ 
ab \prime ′ 
ab \pprime ″ 
ab \ppprime ‴ 
ab \backprime ‵ 
ab \backpprime ‶ 
ab \backppprime ‷ 
ab \guilsinglleft ‹ 
ab \guilsinglright › 
ab \bangbang ‼ 
ab \tieconcat ⁀ 
ab \interrobang ⁉ 
ab \pppprime ⁗ 
ab \tricolon ⁝ 
ab \nolinebreak ⁠ 
ab \^0 ⁰ 
ab \^i ⁱ 
ab \^4 ⁴ 
ab \^5 ⁵ 
ab \^6 ⁶ 
ab \^7 ⁷ 
ab \^8 ⁸ 
ab \^9 ⁹ 
ab \^+ ⁺ 
ab \^- ⁻ 
ab \^= ⁼ 
ab \^( ⁽ 
ab \^) ⁾ 
ab \^n ⁿ 
ab \_0 ₀ 
ab \_1 ₁ 
ab \_2 ₂ 
ab \_3 ₃ 
ab \_4 ₄ 
ab \_5 ₅ 
ab \_6 ₆ 
ab \_7 ₇ 
ab \_8 ₈ 
ab \_9 ₉ 
ab \_+ ₊ 
ab \_- ₋ 
ab \_= ₌ 
ab \_( ₍ 
ab \_) ₎ 
ab \_a ₐ 
ab \_e ₑ 
ab \_o ₒ 
ab \_x ₓ 
ab \_schwa ₔ 
ab \_h ₕ 
ab \_k ₖ 
ab \_l ₗ 
ab \_m ₘ 
ab \_n ₙ 
ab \_p ₚ 
ab \_s ₛ 
ab \_t ₜ 
ab \pes ₧ 
ab \euro € 
ab \leftharpoonaccent '⃐ 
ab \rightharpoonaccent '⃑ 
ab \vertoverlay '⃒ 
ab \overleftarrow '⃖ 
ab \vec '⃗ 
ab \dddot '⃛ 
ab \ddddot '⃜ 
ab \enclosecircle '⃝ 
ab \enclosesquare '⃞ 
ab \enclosediamond '⃟ 
ab \overleftrightarrow '⃡ 
ab \enclosetriangle '⃤ 
ab \annuity '⃧ 
ab \threeunderdot '⃨ 
ab \widebridgeabove '⃩ 
ab \underrightharpoondown '⃬ 
ab \underleftharpoondown '⃭ 
ab \underleftarrow '⃮ 
ab \underrightarrow '⃯ 
ab \asteraccent '⃰ 
ab \bbC ℂ 
ab \eulermascheroni ℇ 
ab \scrg ℊ 
ab \scrH ℋ 
ab \frakH ℌ 
ab \bbH ℍ 
ab \planck ℎ 
ab \hslash ℏ 
ab \scrI ℐ 
ab \Im ℑ 
ab \scrL ℒ 
ab \ell ℓ 
ab \bbN ℕ 
ab \numero № 
ab \wp ℘ 
ab \bbP ℙ 
ab \bbQ ℚ 
ab \scrR ℛ 
ab \Re ℜ 
ab \bbR ℝ 
ab \xrat ℞ 
ab \trademark ™ 
ab \tm ™ 
ab \bbZ ℤ 
ab \ohm Ω 
ab \mho ℧ 
ab \frakZ ℨ 
ab \turnediota ℩ 
ab \Angstrom Å 
ab \scrB ℬ 
ab \frakC ℭ 
ab \scre ℯ 
ab \euler ℯ 
ab \scrE ℰ 
ab \scrF ℱ 
ab \Finv Ⅎ 
ab \scrM ℳ 
ab \scro ℴ 
ab \aleph ℵ 
ab \beth ℶ 
ab \gimel ℷ 
ab \daleth ℸ 
ab \information_source ℹ 
ab \bbpi ℼ 
ab \bbgamma ℽ 
ab \bbGamma ℾ 
ab \bbPi ℿ 
ab \bbsum ⅀ 
ab \Game ⅁ 
ab \sansLturned ⅂ 
ab \sansLmirrored ⅃ 
ab \Yup ⅄ 
ab \bbiD ⅅ 
ab \bbid ⅆ 
ab \bbie ⅇ 
ab \bbii ⅈ 
ab \bbij ⅉ 
ab \PropertyLine ⅊ 
ab \upand ⅋ 
ab \1/7 ⅐ 
ab \1/9 ⅑ 
ab \1/10 ⅒ 
ab \1/3 ⅓ 
ab \2/3 ⅔ 
ab \1/5 ⅕ 
ab \2/5 ⅖ 
ab \3/5 ⅗ 
ab \4/5 ⅘ 
ab \1/6 ⅙ 
ab \5/6 ⅚ 
ab \1/8 ⅛ 
ab \3/8 ⅜ 
ab \5/8 ⅝ 
ab \7/8 ⅞ 
ab \1/ ⅟ 
ab \0/3 ↉ 
ab \leftarrow ← 
ab \uparrow ↑ 
ab \to → 
ab \rightarrow → 
ab \downarrow ↓ 
ab \leftrightarrow ↔ 
ab \left_right_arrow ↔ 
ab \updownarrow ↕ 
ab \arrow_up_down ↕ 
ab \nwarrow ↖ 
ab \arrow_upper_left ↖ 
ab \nearrow ↗ 
ab \arrow_upper_right ↗ 
ab \searrow ↘ 
ab \arrow_lower_right ↘ 
ab \swarrow ↙ 
ab \arrow_lower_left ↙ 
ab \nleftarrow ↚ 
ab \nrightarrow ↛ 
ab \leftwavearrow ↜ 
ab \rightwavearrow ↝ 
ab \twoheadleftarrow ↞ 
ab \twoheaduparrow ↟ 
ab \twoheadrightarrow ↠ 
ab \twoheaddownarrow ↡ 
ab \leftarrowtail ↢ 
ab \rightarrowtail ↣ 
ab \mapsfrom ↤ 
ab \mapsup ↥ 
ab \mapsto ↦ 
ab \mapsdown ↧ 
ab \updownarrowbar ↨ 
ab \hookleftarrow ↩ 
ab \leftwards_arrow_with_hook ↩ 
ab \hookrightarrow ↪ 
ab \arrow_right_hook ↪ 
ab \looparrowleft ↫ 
ab \looparrowright ↬ 
ab \leftrightsquigarrow ↭ 
ab \nleftrightarrow ↮ 
ab \downzigzagarrow ↯ 
ab \Lsh ↰ 
ab \Rsh ↱ 
ab \Ldsh ↲ 
ab \Rdsh ↳ 
ab \linefeed ↴ 
ab \carriagereturn ↵ 
ab \curvearrowleft ↶ 
ab \curvearrowright ↷ 
ab \barovernorthwestarrow ↸ 
ab \barleftarrowrightarrowbar ↹ 
ab \circlearrowleft ↺ 
ab \circlearrowright ↻ 
ab \leftharpoonup ↼ 
ab \leftharpoondown ↽ 
ab \upharpoonright ↾ 
ab \upharpoonleft ↿ 
ab \rightharpoonup ⇀ 
ab \rightharpoondown ⇁ 
ab \downharpoonright ⇂ 
ab \downharpoonleft ⇃ 
ab \rightleftarrows ⇄ 
ab \dblarrowupdown ⇅ 
ab \leftrightarrows ⇆ 
ab \leftleftarrows ⇇ 
ab \upuparrows ⇈ 
ab \rightrightarrows ⇉ 
ab \downdownarrows ⇊ 
ab \leftrightharpoons ⇋ 
ab \rightleftharpoons ⇌ 
ab \nLeftarrow ⇍ 
ab \nLeftrightarrow ⇎ 
ab \nRightarrow ⇏ 
ab \Leftarrow ⇐ 
ab \Uparrow ⇑ 
ab \Rightarrow ⇒ 
ab \Downarrow ⇓ 
ab \Leftrightarrow ⇔ 
ab \Updownarrow ⇕ 
ab \Nwarrow ⇖ 
ab \Nearrow ⇗ 
ab \Searrow ⇘ 
ab \Swarrow ⇙ 
ab \Lleftarrow ⇚ 
ab \Rrightarrow ⇛ 
ab \leftsquigarrow ⇜ 
ab \rightsquigarrow ⇝ 
ab \nHuparrow ⇞ 
ab \nHdownarrow ⇟ 
ab \leftdasharrow ⇠ 
ab \updasharrow ⇡ 
ab \rightdasharrow ⇢ 
ab \downdasharrow ⇣ 
ab \barleftarrow ⇤ 
ab \rightarrowbar ⇥ 
ab \leftwhitearrow ⇦ 
ab \upwhitearrow ⇧ 
ab \rightwhitearrow ⇨ 
ab \downwhitearrow ⇩ 
ab \whitearrowupfrombar ⇪ 
ab \circleonrightarrow ⇴ 
ab \DownArrowUpArrow ⇵ 
ab \rightthreearrows ⇶ 
ab \nvleftarrow ⇷ 
ab \nvrightarrow ⇸ 
ab \nvleftrightarrow ⇹ 
ab \nVleftarrow ⇺ 
ab \nVrightarrow ⇻ 
ab \nVleftrightarrow ⇼ 
ab \leftarrowtriangle ⇽ 
ab \rightarrowtriangle ⇾ 
ab \leftrightarrowtriangle ⇿ 
ab \forall ∀ 
ab \complement ∁ 
ab \partial ∂ 
ab \exists ∃ 
ab \nexists ∄ 
ab \varnothing ∅ 
ab \emptyset ∅ 
ab \increment ∆ 
ab \del ∇ 
ab \nabla ∇ 
ab \in ∈ 
ab \notin ∉ 
ab \smallin ∊ 
ab \ni ∋ 
ab \nni ∌ 
ab \smallni ∍ 
ab \QED ∎ 
ab \prod ∏ 
ab \coprod ∐ 
ab \sum ∑ 
ab \minus − 
ab \mp ∓ 
ab \dotplus ∔ 
ab \setminus ∖ 
ab \ast ∗ 
ab \circ ∘ 
ab \vysmblkcircle ∙ 
ab \surd √ 
ab \sqrt √ 
ab \cbrt ∛ 
ab \fourthroot ∜ 
ab \propto ∝ 
ab \infty ∞ 
ab \rightangle ∟ 
ab \angle ∠ 
ab \measuredangle ∡ 
ab \sphericalangle ∢ 
ab \mid ∣ 
ab \nmid ∤ 
ab \parallel ∥ 
ab \nparallel ∦ 
ab \wedge ∧ 
ab \vee ∨ 
ab \cap ∩ 
ab \cup ∪ 
ab \int ∫ 
ab \iint ∬ 
ab \iiint ∭ 
ab \oint ∮ 
ab \oiint ∯ 
ab \oiiint ∰ 
ab \clwintegral ∱ 
ab \varointclockwise ∲ 
ab \ointctrclockwise ∳ 
ab \therefore ∴ 
ab \because ∵ 
ab \Colon ∷ 
ab \dotminus ∸ 
ab \dotsminusdots ∺ 
ab \kernelcontraction ∻ 
ab \sim ∼ 
ab \backsim ∽ 
ab \lazysinv ∾ 
ab \sinewave ∿ 
ab \wr ≀ 
ab \nsim ≁ 
ab \eqsim ≂ 
ab \neqsim ≂̸ 
ab \simeq ≃ 
ab \nsime ≄ 
ab \cong ≅ 
ab \approxnotequal ≆ 
ab \ncong ≇ 
ab \approx ≈ 
ab \napprox ≉ 
ab \approxeq ≊ 
ab \tildetrpl ≋ 
ab \allequal ≌ 
ab \asymp ≍ 
ab \Bumpeq ≎ 
ab \nBumpeq ≎̸ 
ab \bumpeq ≏ 
ab \nbumpeq ≏̸ 
ab \doteq ≐ 
ab \Doteq ≑ 
ab \fallingdotseq ≒ 
ab \risingdotseq ≓ 
ab \coloneq ≔ 
ab \eqcolon ≕ 
ab \eqcirc ≖ 
ab \circeq ≗ 
ab \arceq ≘ 
ab \wedgeq ≙ 
ab \veeeq ≚ 
ab \starequal ≛ 
ab \triangleq ≜ 
ab \eqdef ≝ 
ab \measeq ≞ 
ab \questeq ≟ 
ab \ne ≠ 
ab \equiv ≡ 
ab \nequiv ≢ 
ab \Equiv ≣ 
ab \le ≤ 
ab \leq ≤ 
ab \ge ≥ 
ab \geq ≥ 
ab \leqq ≦ 
ab \geqq ≧ 
ab \lneqq ≨ 
ab \lvertneqq ≨︀ 
ab \gneqq ≩ 
ab \gvertneqq ≩︀ 
ab \ll ≪ 
ab \NotLessLess ≪̸ 
ab \gg ≫ 
ab \NotGreaterGreater ≫̸ 
ab \between ≬ 
ab \nasymp ≭ 
ab \nless ≮ 
ab \ngtr ≯ 
ab \nleq ≰ 
ab \ngeq ≱ 
ab \lesssim ≲ 
ab \gtrsim ≳ 
ab \nlesssim ≴ 
ab \ngtrsim ≵ 
ab \lessgtr ≶ 
ab \gtrless ≷ 
ab \notlessgreater ≸ 
ab \notgreaterless ≹ 
ab \prec ≺ 
ab \succ ≻ 
ab \preccurlyeq ≼ 
ab \succcurlyeq ≽ 
ab \precsim ≾ 
ab \nprecsim ≾̸ 
ab \succsim ≿ 
ab \nsuccsim ≿̸ 
ab \nprec ⊀ 
ab \nsucc ⊁ 
ab \subset ⊂ 
ab \supset ⊃ 
ab \nsubset ⊄ 
ab \nsupset ⊅ 
ab \subseteq ⊆ 
ab \supseteq ⊇ 
ab \nsubseteq ⊈ 
ab \nsupseteq ⊉ 
ab \subsetneq ⊊ 
ab \varsubsetneqq ⊊︀ 
ab \supsetneq ⊋ 
ab \varsupsetneq ⊋︀ 
ab \cupdot ⊍ 
ab \uplus ⊎ 
ab \sqsubset ⊏ 
ab \NotSquareSubset ⊏̸ 
ab \sqsupset ⊐ 
ab \NotSquareSuperset ⊐̸ 
ab \sqsubseteq ⊑ 
ab \sqsupseteq ⊒ 
ab \sqcap ⊓ 
ab \sqcup ⊔ 
ab \oplus ⊕ 
ab \ominus ⊖ 
ab \otimes ⊗ 
ab \oslash ⊘ 
ab \odot ⊙ 
ab \circledcirc ⊚ 
ab \circledast ⊛ 
ab \circledequal ⊜ 
ab \circleddash ⊝ 
ab \boxplus ⊞ 
ab \boxminus ⊟ 
ab \boxtimes ⊠ 
ab \boxdot ⊡ 
ab \vdash ⊢ 
ab \dashv ⊣ 
ab \top ⊤ 
ab \bot ⊥ 
ab \models ⊧ 
ab \vDash ⊨ 
ab \Vdash ⊩ 
ab \Vvdash ⊪ 
ab \VDash ⊫ 
ab \nvdash ⊬ 
ab \nvDash ⊭ 
ab \nVdash ⊮ 
ab \nVDash ⊯ 
ab \prurel ⊰ 
ab \scurel ⊱ 
ab \vartriangleleft ⊲ 
ab \vartriangleright ⊳ 
ab \trianglelefteq ⊴ 
ab \trianglerighteq ⊵ 
ab \original ⊶ 
ab \image ⊷ 
ab \multimap ⊸ 
ab \hermitconjmatrix ⊹ 
ab \intercal ⊺ 
ab \veebar ⊻ 
ab \xor ⊻ 
ab \barwedge ⊼ 
ab \barvee ⊽ 
ab \rightanglearc ⊾ 
ab \varlrtriangle ⊿ 
ab \bigwedge ⋀ 
ab \bigvee ⋁ 
ab \bigcap ⋂ 
ab \bigcup ⋃ 
ab \diamond ⋄ 
ab \cdot ⋅ 
ab \star ⋆ 
ab \divideontimes ⋇ 
ab \bowtie ⋈ 
ab \ltimes ⋉ 
ab \rtimes ⋊ 
ab \leftthreetimes ⋋ 
ab \rightthreetimes ⋌ 
ab \backsimeq ⋍ 
ab \curlyvee ⋎ 
ab \curlywedge ⋏ 
ab \Subset ⋐ 
ab \Supset ⋑ 
ab \Cap ⋒ 
ab \Cup ⋓ 
ab \pitchfork ⋔ 
ab \equalparallel ⋕ 
ab \lessdot ⋖ 
ab \gtrdot ⋗ 
ab \verymuchless ⋘ 
ab \ggg ⋙ 
ab \lesseqgtr ⋚ 
ab \gtreqless ⋛ 
ab \eqless ⋜ 
ab \eqgtr ⋝ 
ab \curlyeqprec ⋞ 
ab \curlyeqsucc ⋟ 
ab \npreccurlyeq ⋠ 
ab \nsucccurlyeq ⋡ 
ab \nsqsubseteq ⋢ 
ab \nsqsupseteq ⋣ 
ab \sqsubsetneq ⋤ 
ab \sqspne ⋥ 
ab \lnsim ⋦ 
ab \gnsim ⋧ 
ab \precnsim ⋨ 
ab \succnsim ⋩ 
ab \ntriangleleft ⋪ 
ab \ntriangleright ⋫ 
ab \ntrianglelefteq ⋬ 
ab \ntrianglerighteq ⋭ 
ab \vdots ⋮ 
ab \cdots ⋯ 
ab \adots ⋰ 
ab \ddots ⋱ 
ab \disin ⋲ 
ab \varisins ⋳ 
ab \isins ⋴ 
ab \isindot ⋵ 
ab \varisinobar ⋶ 
ab \isinobar ⋷ 
ab \isinvb ⋸ 
ab \isinE ⋹ 
ab \nisd ⋺ 
ab \varnis ⋻ 
ab \nis ⋼ 
ab \varniobar ⋽ 
ab \niobar ⋾ 
ab \bagmember ⋿ 
ab \diameter ⌀ 
ab \house ⌂ 
ab \varbarwedge ⌅ 
ab \vardoublebarwedge ⌆ 
ab \lceil ⌈ 
ab \rceil ⌉ 
ab \lfloor ⌊ 
ab \rfloor ⌋ 
ab \invnot ⌐ 
ab \sqlozenge ⌑ 
ab \profline ⌒ 
ab \profsurf ⌓ 
ab \recorder ⌕ 
ab \viewdata ⌗ 
ab \turnednot ⌙ 
ab \watch ⌚ 
ab \hourglass ⌛ 
ab \ulcorner ⌜ 
ab \urcorner ⌝ 
ab \llcorner ⌞ 
ab \lrcorner ⌟ 
ab \frown ⌢ 
ab \smile ⌣ 
ab \varhexagonlrbonds ⌬ 
ab \conictaper ⌲ 
ab \topbot ⌶ 
ab \obar ⌽ 
ab \notslash ⌿ 
ab \notbackslash ⍀ 
ab \boxupcaret ⍓ 
ab \boxquestion ⍰ 
ab \hexagon ⎔ 
ab \dlcorn ⎣ 
ab \lmoustache ⎰ 
ab \rmoustache ⎱ 
ab \overbracket ⎴ 
ab \underbracket ⎵ 
ab \bbrktbrk ⎶ 
ab \sqrtbottom ⎷ 
ab \lvboxline ⎸ 
ab \rvboxline ⎹ 
ab \varcarriagereturn ⏎ 
ab \overbrace ⏞ 
ab \underbrace ⏟ 
ab \trapezium ⏢ 
ab \benzenr ⏣ 
ab \strns ⏤ 
ab \fltns ⏥ 
ab \accurrent ⏦ 
ab \elinters ⏧ 
ab \fast_forward ⏩ 
ab \rewind ⏪ 
ab \arrow_double_up ⏫ 
ab \arrow_double_down ⏬ 
ab \alarm_clock ⏰ 
ab \hourglass_flowing_sand ⏳ 
ab \blanksymbol ␢ 
ab \visiblespace ␣ 
ab \m Ⓜ 
ab \circledS Ⓢ 
ab \dshfnc ┆ 
ab \sqfnw ┙ 
ab \diagup ╱ 
ab \diagdown ╲ 
ab \blockuphalf ▀ 
ab \blocklowhalf ▄ 
ab \blockfull █ 
ab \blocklefthalf ▌ 
ab \blockrighthalf ▐ 
ab \blockqtrshaded ░ 
ab \blockhalfshaded ▒ 
ab \blockthreeqtrshaded ▓ 
ab \blacksquare ■ 
ab \square □ 
ab \squoval ▢ 
ab \blackinwhitesquare ▣ 
ab \squarehfill ▤ 
ab \squarevfill ▥ 
ab \squarehvfill ▦ 
ab \squarenwsefill ▧ 
ab \squareneswfill ▨ 
ab \squarecrossfill ▩ 
ab \smblksquare ▪ 
ab \black_small_square ▪ 
ab \smwhtsquare ▫ 
ab \white_small_square ▫ 
ab \hrectangleblack ▬ 
ab \hrectangle ▭ 
ab \vrectangleblack ▮ 
ab \vrecto ▯ 
ab \parallelogramblack ▰ 
ab \parallelogram ▱ 
ab \bigblacktriangleup ▲ 
ab \bigtriangleup △ 
ab \blacktriangle ▴ 
ab \vartriangle ▵ 
ab \blacktriangleright ▶ 
ab \arrow_forward ▶ 
ab \triangleright ▷ 
ab \smallblacktriangleright ▸ 
ab \smalltriangleright ▹ 
ab \blackpointerright ► 
ab \whitepointerright ▻ 
ab \bigblacktriangledown ▼ 
ab \bigtriangledown ▽ 
ab \blacktriangledown ▾ 
ab \triangledown ▿ 
ab \blacktriangleleft ◀ 
ab \arrow_backward ◀ 
ab \triangleleft ◁ 
ab \smallblacktriangleleft ◂ 
ab \smalltriangleleft ◃ 
ab \blackpointerleft ◄ 
ab \whitepointerleft ◅ 
ab \mdlgblkdiamond ◆ 
ab \mdlgwhtdiamond ◇ 
ab \blackinwhitediamond ◈ 
ab \fisheye ◉ 
ab \lozenge ◊ 
ab \bigcirc ○ 
ab \dottedcircle ◌ 
ab \circlevertfill ◍ 
ab \bullseye ◎ 
ab \mdlgblkcircle ● 
ab \cirfl ◐ 
ab \cirfr ◑ 
ab \cirfb ◒ 
ab \circletophalfblack ◓ 
ab \circleurquadblack ◔ 
ab \blackcircleulquadwhite ◕ 
ab \blacklefthalfcircle ◖ 
ab \blackrighthalfcircle ◗ 
ab \rvbull ◘ 
ab \inversewhitecircle ◙ 
ab \invwhiteupperhalfcircle ◚ 
ab \invwhitelowerhalfcircle ◛ 
ab \ularc ◜ 
ab \urarc ◝ 
ab \lrarc ◞ 
ab \llarc ◟ 
ab \topsemicircle ◠ 
ab \botsemicircle ◡ 
ab \lrblacktriangle ◢ 
ab \llblacktriangle ◣ 
ab \ulblacktriangle ◤ 
ab \urblacktriangle ◥ 
ab \smwhtcircle ◦ 
ab \sqfl ◧ 
ab \sqfr ◨ 
ab \squareulblack ◩ 
ab \sqfse ◪ 
ab \boxbar ◫ 
ab \trianglecdot ◬ 
ab \triangleleftblack ◭ 
ab \trianglerightblack ◮ 
ab \lgwhtcircle ◯ 
ab \squareulquad ◰ 
ab \squarellquad ◱ 
ab \squarelrquad ◲ 
ab \squareurquad ◳ 
ab \circleulquad ◴ 
ab \circlellquad ◵ 
ab \circlelrquad ◶ 
ab \circleurquad ◷ 
ab \ultriangle ◸ 
ab \urtriangle ◹ 
ab \lltriangle ◺ 
ab \mdwhtsquare ◻ 
ab \white_medium_square ◻ 
ab \mdblksquare ◼ 
ab \black_medium_square ◼ 
ab \mdsmwhtsquare ◽ 
ab \white_medium_small_square ◽ 
ab \mdsmblksquare ◾ 
ab \black_medium_small_square ◾ 
ab \lrtriangle ◿ 
ab \sunny ☀ 
ab \cloud ☁ 
ab \bigstar ★ 
ab \bigwhitestar ☆ 
ab \astrosun ☉ 
ab \phone ☎ 
ab \ballot_box_with_check ☑ 
ab \umbrella ☔ 
ab \coffee ☕ 
ab \point_up ☝ 
ab \danger ☡ 
ab \relaxed ☺ 
ab \blacksmiley ☻ 
ab \sun ☼ 
ab \rightmoon ☽ 
ab \leftmoon ☾ 
ab \mercury ☿ 
ab \venus ♀ 
ab \female ♀ 
ab \male ♂ 
ab \mars ♂ 
ab \jupiter ♃ 
ab \saturn ♄ 
ab \uranus ♅ 
ab \neptune ♆ 
ab \pluto ♇ 
ab \aries ♈ 
ab \aries ♈ 
ab \taurus ♉ 
ab \taurus ♉ 
ab \gemini ♊ 
ab \gemini ♊ 
ab \cancer ♋ 
ab \cancer ♋ 
ab \leo ♌ 
ab \leo ♌ 
ab \virgo ♍ 
ab \virgo ♍ 
ab \libra ♎ 
ab \libra ♎ 
ab \scorpio ♏ 
ab \scorpius ♏ 
ab \sagittarius ♐ 
ab \sagittarius ♐ 
ab \capricornus ♑ 
ab \capricorn ♑ 
ab \aquarius ♒ 
ab \aquarius ♒ 
ab \pisces ♓ 
ab \pisces ♓ 
ab \spadesuit ♠ 
ab \spades ♠ 
ab \heartsuit ♡ 
ab \diamondsuit ♢ 
ab \clubsuit ♣ 
ab \clubs ♣ 
ab \varspadesuit ♤ 
ab \varheartsuit ♥ 
ab \hearts ♥ 
ab \vardiamondsuit ♦ 
ab \diamonds ♦ 
ab \varclubsuit ♧ 
ab \hotsprings ♨ 
ab \quarternote ♩ 
ab \eighthnote ♪ 
ab \twonotes ♫ 
ab \flat ♭ 
ab \natural ♮ 
ab \sharp ♯ 
ab \recycle ♻ 
ab \acidfree ♾ 
ab \wheelchair ♿ 
ab \dicei ⚀ 
ab \diceii ⚁ 
ab \diceiii ⚂ 
ab \diceiv ⚃ 
ab \dicev ⚄ 
ab \dicevi ⚅ 
ab \circledrightdot ⚆ 
ab \circledtwodots ⚇ 
ab \blackcircledrightdot ⚈ 
ab \blackcircledtwodots ⚉ 
ab \anchor ⚓ 
ab \warning ⚠ 
ab \zap ⚡ 
ab \hermaphrodite ⚥ 
ab \mdwhtcircle ⚪ 
ab \white_circle ⚪ 
ab \mdblkcircle ⚫ 
ab \black_circle ⚫ 
ab \mdsmwhtcircle ⚬ 
ab \neuter ⚲ 
ab \soccer ⚽ 
ab \baseball ⚾ 
ab \snowman ⛄ 
ab \partly_sunny ⛅ 
ab \ophiuchus ⛎ 
ab \no_entry ⛔ 
ab \church ⛪ 
ab \fountain ⛲ 
ab \golf ⛳ 
ab \boat ⛵ 
ab \tent ⛺ 
ab \fuelpump ⛽ 
ab \scissors ✂ 
ab \white_check_mark ✅ 
ab \airplane ✈ 
ab \email ✉ 
ab \fist ✊ 
ab \hand ✋ 
ab \v ✌ 
ab \pencil2 ✏ 
ab \black_nib ✒ 
ab \checkmark ✓ 
ab \heavy_check_mark ✔ 
ab \heavy_multiplication_x ✖ 
ab \maltese ✠ 
ab \sparkles ✨ 
ab \circledstar ✪ 
ab \eight_spoked_asterisk ✳ 
ab \eight_pointed_black_star ✴ 
ab \varstar ✶ 
ab \dingasterisk ✽ 
ab \snowflake ❄ 
ab \sparkle ❇ 
ab \x ❌ 
ab \negative_squared_cross_mark ❎ 
ab \question ❓ 
ab \grey_question ❔ 
ab \grey_exclamation ❕ 
ab \exclamation ❗ 
ab \heart ❤ 
ab \heavy_plus_sign ➕ 
ab \heavy_minus_sign ➖ 
ab \heavy_division_sign ➗ 
ab \draftingarrow ➛ 
ab \arrow_right ➡ 
ab \curly_loop ➰ 
ab \loop ➿ 
ab \threedangle ⟀ 
ab \whiteinwhitetriangle ⟁ 
ab \perp ⟂ 
ab \bsolhsub ⟈ 
ab \suphsol ⟉ 
ab \wedgedot ⟑ 
ab \upin ⟒ 
ab \leftouterjoin ⟕ 
ab \rightouterjoin ⟖ 
ab \fullouterjoin ⟗ 
ab \bigbot ⟘ 
ab \bigtop ⟙ 
ab \llbracket ⟦ 
ab \openbracketleft ⟦ 
ab \openbracketright ⟧ 
ab \rrbracket ⟧ 
ab \langle ⟨ 
ab \rangle ⟩ 
ab \UUparrow ⟰ 
ab \DDownarrow ⟱ 
ab \longleftarrow ⟵ 
ab \longrightarrow ⟶ 
ab \longleftrightarrow ⟷ 
ab \impliedby ⟸ 
ab \Longleftarrow ⟸ 
ab \implies ⟹ 
ab \Longrightarrow ⟹ 
ab \Longleftrightarrow ⟺ 
ab \iff ⟺ 
ab \longmapsfrom ⟻ 
ab \longmapsto ⟼ 
ab \Longmapsfrom ⟽ 
ab \Longmapsto ⟾ 
ab \longrightsquigarrow ⟿ 
ab \nvtwoheadrightarrow ⤀ 
ab \nVtwoheadrightarrow ⤁ 
ab \nvLeftarrow ⤂ 
ab \nvRightarrow ⤃ 
ab \nvLeftrightarrow ⤄ 
ab \twoheadmapsto ⤅ 
ab \Mapsfrom ⤆ 
ab \Mapsto ⤇ 
ab \downarrowbarred ⤈ 
ab \uparrowbarred ⤉ 
ab \Uuparrow ⤊ 
ab \Ddownarrow ⤋ 
ab \leftbkarrow ⤌ 
ab \bkarow ⤍ 
ab \leftdbkarrow ⤎ 
ab \dbkarow ⤏ 
ab \drbkarrow ⤐ 
ab \rightdotarrow ⤑ 
ab \UpArrowBar ⤒ 
ab \DownArrowBar ⤓ 
ab \nvrightarrowtail ⤔ 
ab \nVrightarrowtail ⤕ 
ab \twoheadrightarrowtail ⤖ 
ab \nvtwoheadrightarrowtail ⤗ 
ab \nVtwoheadrightarrowtail ⤘ 
ab \diamondleftarrow ⤝ 
ab \rightarrowdiamond ⤞ 
ab \diamondleftarrowbar ⤟ 
ab \barrightarrowdiamond ⤠ 
ab \hksearow ⤥ 
ab \hkswarow ⤦ 
ab \tona ⤧ 
ab \toea ⤨ 
ab \tosa ⤩ 
ab \towa ⤪ 
ab \rdiagovfdiag ⤫ 
ab \fdiagovrdiag ⤬ 
ab \seovnearrow ⤭ 
ab \neovsearrow ⤮ 
ab \fdiagovnearrow ⤯ 
ab \rdiagovsearrow ⤰ 
ab \neovnwarrow ⤱ 
ab \nwovnearrow ⤲ 
ab \arrow_heading_up ⤴ 
ab \arrow_heading_down ⤵ 
ab \Rlarr ⥂ 
ab \rLarr ⥄ 
ab \rightarrowplus ⥅ 
ab \leftarrowplus ⥆ 
ab \rarrx ⥇ 
ab \leftrightarrowcircle ⥈ 
ab \twoheaduparrowcircle ⥉ 
ab \leftrightharpoonupdown ⥊ 
ab \leftrightharpoondownup ⥋ 
ab \updownharpoonrightleft ⥌ 
ab \updownharpoonleftright ⥍ 
ab \LeftRightVector ⥎ 
ab \RightUpDownVector ⥏ 
ab \DownLeftRightVector ⥐ 
ab \LeftUpDownVector ⥑ 
ab \LeftVectorBar ⥒ 
ab \RightVectorBar ⥓ 
ab \RightUpVectorBar ⥔ 
ab \RightDownVectorBar ⥕ 
ab \DownLeftVectorBar ⥖ 
ab \DownRightVectorBar ⥗ 
ab \LeftUpVectorBar ⥘ 
ab \LeftDownVectorBar ⥙ 
ab \LeftTeeVector ⥚ 
ab \RightTeeVector ⥛ 
ab \RightUpTeeVector ⥜ 
ab \RightDownTeeVector ⥝ 
ab \DownLeftTeeVector ⥞ 
ab \DownRightTeeVector ⥟ 
ab \LeftUpTeeVector ⥠ 
ab \LeftDownTeeVector ⥡ 
ab \leftharpoonsupdown ⥢ 
ab \upharpoonsleftright ⥣ 
ab \rightharpoonsupdown ⥤ 
ab \downharpoonsleftright ⥥ 
ab \leftrightharpoonsup ⥦ 
ab \leftrightharpoonsdown ⥧ 
ab \rightleftharpoonsup ⥨ 
ab \rightleftharpoonsdown ⥩ 
ab \leftharpoonupdash ⥪ 
ab \dashleftharpoondown ⥫ 
ab \rightharpoonupdash ⥬ 
ab \dashrightharpoondown ⥭ 
ab \UpEquilibrium ⥮ 
ab \ReverseUpEquilibrium ⥯ 
ab \RoundImplies ⥰ 
ab \Vvert ⦀ 
ab \Elroang ⦆ 
ab \ddfnc ⦙ 
ab \measuredangleleft ⦛ 
ab \Angle ⦜ 
ab \rightanglemdot ⦝ 
ab \angles ⦞ 
ab \angdnr ⦟ 
ab \lpargt ⦠ 
ab \sphericalangleup ⦡ 
ab \turnangle ⦢ 
ab \revangle ⦣ 
ab \angleubar ⦤ 
ab \revangleubar ⦥ 
ab \wideangledown ⦦ 
ab \wideangleup ⦧ 
ab \measanglerutone ⦨ 
ab \measanglelutonw ⦩ 
ab \measanglerdtose ⦪ 
ab \measangleldtosw ⦫ 
ab \measangleurtone ⦬ 
ab \measangleultonw ⦭ 
ab \measangledrtose ⦮ 
ab \measangledltosw ⦯ 
ab \revemptyset ⦰ 
ab \emptysetobar ⦱ 
ab \emptysetocirc ⦲ 
ab \emptysetoarr ⦳ 
ab \emptysetoarrl ⦴ 
ab \circledparallel ⦷ 
ab \obslash ⦸ 
ab \odotslashdot ⦼ 
ab \circledwhitebullet ⦾ 
ab \circledbullet ⦿ 
ab \olessthan ⧀ 
ab \ogreaterthan ⧁ 
ab \boxdiag ⧄ 
ab \boxbslash ⧅ 
ab \boxast ⧆ 
ab \boxcircle ⧇ 
ab \Lap ⧊ 
ab \defas ⧋ 
ab \LeftTriangleBar ⧏ 
ab \NotLeftTriangleBar ⧏̸ 
ab \RightTriangleBar ⧐ 
ab \NotRightTriangleBar ⧐̸ 
ab \dualmap ⧟ 
ab \lrtriangleeq ⧡ 
ab \shuffle ⧢ 
ab \eparsl ⧣ 
ab \smeparsl ⧤ 
ab \eqvparsl ⧥ 
ab \blacklozenge ⧫ 
ab \RuleDelayed ⧴ 
ab \dsol ⧶ 
ab \rsolbar ⧷ 
ab \doubleplus ⧺ 
ab \tripleplus ⧻ 
ab \bigodot ⨀ 
ab \bigoplus ⨁ 
ab \bigotimes ⨂ 
ab \bigcupdot ⨃ 
ab \biguplus ⨄ 
ab \bigsqcap ⨅ 
ab \bigsqcup ⨆ 
ab \conjquant ⨇ 
ab \disjquant ⨈ 
ab \bigtimes ⨉ 
ab \modtwosum ⨊ 
ab \sumint ⨋ 
ab \iiiint ⨌ 
ab \intbar ⨍ 
ab \intBar ⨎ 
ab \clockoint ⨏ 
ab \cirfnint ⨐ 
ab \awint ⨑ 
ab \rppolint ⨒ 
ab \scpolint ⨓ 
ab \npolint ⨔ 
ab \pointint ⨕ 
ab \sqrint ⨖ 
ab \intx ⨘ 
ab \intcap ⨙ 
ab \intcup ⨚ 
ab \upint ⨛ 
ab \lowint ⨜ 
ab \Join ⨝ 
ab \join ⨝ 
ab \ringplus ⨢ 
ab \plushat ⨣ 
ab \simplus ⨤ 
ab \plusdot ⨥ 
ab \plussim ⨦ 
ab \plussubtwo ⨧ 
ab \plustrif ⨨ 
ab \commaminus ⨩ 
ab \minusdot ⨪ 
ab \minusfdots ⨫ 
ab \minusrdots ⨬ 
ab \opluslhrim ⨭ 
ab \oplusrhrim ⨮ 
ab \Times ⨯ 
ab \dottimes ⨰ 
ab \timesbar ⨱ 
ab \btimes ⨲ 
ab \smashtimes ⨳ 
ab \otimeslhrim ⨴ 
ab \otimesrhrim ⨵ 
ab \otimeshat ⨶ 
ab \Otimes ⨷ 
ab \odiv ⨸ 
ab \triangleplus ⨹ 
ab \triangleminus ⨺ 
ab \triangletimes ⨻ 
ab \intprod ⨼ 
ab \intprodr ⨽ 
ab \amalg ⨿ 
ab \capdot ⩀ 
ab \uminus ⩁ 
ab \barcup ⩂ 
ab \barcap ⩃ 
ab \capwedge ⩄ 
ab \cupvee ⩅ 
ab \twocups ⩊ 
ab \twocaps ⩋ 
ab \closedvarcup ⩌ 
ab \closedvarcap ⩍ 
ab \Sqcap ⩎ 
ab \Sqcup ⩏ 
ab \closedvarcupsmashprod ⩐ 
ab \wedgeodot ⩑ 
ab \veeodot ⩒ 
ab \And ⩓ 
ab \Or ⩔ 
ab \wedgeonwedge ⩕ 
ab \ElOr ⩖ 
ab \bigslopedvee ⩗ 
ab \bigslopedwedge ⩘ 
ab \wedgemidvert ⩚ 
ab \veemidvert ⩛ 
ab \midbarwedge ⩜ 
ab \midbarvee ⩝ 
ab \perspcorrespond ⩞ 
ab \minhat ⩟ 
ab \wedgedoublebar ⩠ 
ab \varveebar ⩡ 
ab \doublebarvee ⩢ 
ab \veedoublebar ⩣ 
ab \eqdot ⩦ 
ab \dotequiv ⩧ 
ab \dotsim ⩪ 
ab \simrdots ⩫ 
ab \simminussim ⩬ 
ab \congdot ⩭ 
ab \asteq ⩮ 
ab \hatapprox ⩯ 
ab \approxeqq ⩰ 
ab \eqqplus ⩱ 
ab \pluseqq ⩲ 
ab \eqqsim ⩳ 
ab \Coloneq ⩴ 
ab \Equal ⩵ 
ab \eqeqeq ⩶ 
ab \ddotseq ⩷ 
ab \equivDD ⩸ 
ab \ltcir ⩹ 
ab \gtcir ⩺ 
ab \ltquest ⩻ 
ab \gtquest ⩼ 
ab \leqslant ⩽ 
ab \nleqslant ⩽̸ 
ab \geqslant ⩾ 
ab \ngeqslant ⩾̸ 
ab \lesdot ⩿ 
ab \gesdot ⪀ 
ab \lesdoto ⪁ 
ab \gesdoto ⪂ 
ab \lesdotor ⪃ 
ab \gesdotol ⪄ 
ab \lessapprox ⪅ 
ab \gtrapprox ⪆ 
ab \lneq ⪇ 
ab \gneq ⪈ 
ab \lnapprox ⪉ 
ab \gnapprox ⪊ 
ab \lesseqqgtr ⪋ 
ab \gtreqqless ⪌ 
ab \lsime ⪍ 
ab \gsime ⪎ 
ab \lsimg ⪏ 
ab \gsiml ⪐ 
ab \lgE ⪑ 
ab \glE ⪒ 
ab \lesges ⪓ 
ab \gesles ⪔ 
ab \eqslantless ⪕ 
ab \eqslantgtr ⪖ 
ab \elsdot ⪗ 
ab \egsdot ⪘ 
ab \eqqless ⪙ 
ab \eqqgtr ⪚ 
ab \eqqslantless ⪛ 
ab \eqqslantgtr ⪜ 
ab \simless ⪝ 
ab \simgtr ⪞ 
ab \simlE ⪟ 
ab \simgE ⪠ 
ab \NestedLessLess ⪡ 
ab \NotNestedLessLess ⪡̸ 
ab \NestedGreaterGreater ⪢ 
ab \NotNestedGreaterGreater ⪢̸ 
ab \partialmeetcontraction ⪣ 
ab \glj ⪤ 
ab \gla ⪥ 
ab \ltcc ⪦ 
ab \gtcc ⪧ 
ab \lescc ⪨ 
ab \gescc ⪩ 
ab \smt ⪪ 
ab \lat ⪫ 
ab \smte ⪬ 
ab \late ⪭ 
ab \bumpeqq ⪮ 
ab \preceq ⪯ 
ab \npreceq ⪯̸ 
ab \succeq ⪰ 
ab \nsucceq ⪰̸ 
ab \precneq ⪱ 
ab \succneq ⪲ 
ab \preceqq ⪳ 
ab \succeqq ⪴ 
ab \precneqq ⪵ 
ab \succneqq ⪶ 
ab \precapprox ⪷ 
ab \succapprox ⪸ 
ab \precnapprox ⪹ 
ab \succnapprox ⪺ 
ab \Prec ⪻ 
ab \Succ ⪼ 
ab \subsetdot ⪽ 
ab \supsetdot ⪾ 
ab \subsetplus ⪿ 
ab \supsetplus ⫀ 
ab \submult ⫁ 
ab \supmult ⫂ 
ab \subedot ⫃ 
ab \supedot ⫄ 
ab \subseteqq ⫅ 
ab \nsubseteqq ⫅̸ 
ab \supseteqq ⫆ 
ab \nsupseteqq ⫆̸ 
ab \subsim ⫇ 
ab \supsim ⫈ 
ab \subsetapprox ⫉ 
ab \supsetapprox ⫊ 
ab \subsetneqq ⫋ 
ab \supsetneqq ⫌ 
ab \lsqhook ⫍ 
ab \rsqhook ⫎ 
ab \csub ⫏ 
ab \csup ⫐ 
ab \csube ⫑ 
ab \csupe ⫒ 
ab \subsup ⫓ 
ab \supsub ⫔ 
ab \subsub ⫕ 
ab \supsup ⫖ 
ab \suphsub ⫗ 
ab \supdsub ⫘ 
ab \forkv ⫙ 
ab \mlcp ⫛ 
ab \forks ⫝̸ 
ab \forksnot ⫝ 
ab \dashV ⫣ 
ab \Dashv ⫤ 
ab \interleave ⫴ 
ab \tdcol ⫶ 
ab \lllnest ⫷ 
ab \gggnest ⫸ 
ab \leqqslant ⫹ 
ab \geqqslant ⫺ 
ab \arrow_left ⬅ 
ab \arrow_up ⬆ 
ab \arrow_down ⬇ 
ab \squaretopblack ⬒ 
ab \squarebotblack ⬓ 
ab \squareurblack ⬔ 
ab \squarellblack ⬕ 
ab \diamondleftblack ⬖ 
ab \diamondrightblack ⬗ 
ab \diamondtopblack ⬘ 
ab \diamondbotblack ⬙ 
ab \dottedsquare ⬚ 
ab \lgblksquare ⬛ 
ab \black_large_square ⬛ 
ab \lgwhtsquare ⬜ 
ab \white_large_square ⬜ 
ab \vysmblksquare ⬝ 
ab \vysmwhtsquare ⬞ 
ab \pentagonblack ⬟ 
ab \pentagon ⬠ 
ab \varhexagon ⬡ 
ab \varhexagonblack ⬢ 
ab \hexagonblack ⬣ 
ab \lgblkcircle ⬤ 
ab \mdblkdiamond ⬥ 
ab \mdwhtdiamond ⬦ 
ab \mdblklozenge ⬧ 
ab \mdwhtlozenge ⬨ 
ab \smblkdiamond ⬩ 
ab \smblklozenge ⬪ 
ab \smwhtlozenge ⬫ 
ab \blkhorzoval ⬬ 
ab \whthorzoval ⬭ 
ab \blkvertoval ⬮ 
ab \whtvertoval ⬯ 
ab \circleonleftarrow ⬰ 
ab \leftthreearrows ⬱ 
ab \leftarrowonoplus ⬲ 
ab \longleftsquigarrow ⬳ 
ab \nvtwoheadleftarrow ⬴ 
ab \nVtwoheadleftarrow ⬵ 
ab \twoheadmapsfrom ⬶ 
ab \twoheadleftdbkarrow ⬷ 
ab \leftdotarrow ⬸ 
ab \nvleftarrowtail ⬹ 
ab \nVleftarrowtail ⬺ 
ab \twoheadleftarrowtail ⬻ 
ab \nvtwoheadleftarrowtail ⬼ 
ab \nVtwoheadleftarrowtail ⬽ 
ab \leftarrowx ⬾ 
ab \leftcurvedarrow ⬿ 
ab \equalleftarrow ⭀ 
ab \bsimilarleftarrow ⭁ 
ab \leftarrowbackapprox ⭂ 
ab \rightarrowgtr ⭃ 
ab \rightarrowsupset ⭄ 
ab \LLeftarrow ⭅ 
ab \RRightarrow ⭆ 
ab \bsimilarrightarrow ⭇ 
ab \rightarrowbackapprox ⭈ 
ab \similarleftarrow ⭉ 
ab \leftarrowapprox ⭊ 
ab \leftarrowbsimilar ⭋ 
ab \rightarrowbsimilar ⭌ 
ab \medwhitestar ⭐ 
ab \star ⭐ 
ab \medblackstar ⭑ 
ab \smwhitestar ⭒ 
ab \rightpentagonblack ⭓ 
ab \rightpentagon ⭔ 
ab \o ⭕ 
ab \_j ⱼ 
ab \^V ⱽ 
ab \postalmark 〒 
ab \wavy_dash 〰 
ab \part_alternation_mark 〽 
ab \congratulations ㊗ 
ab \secret ㊙ 
ab \bfA 𝐀 
ab \bfB 𝐁 
ab \bfC 𝐂 
ab \bfD 𝐃 
ab \bfE 𝐄 
ab \bfF 𝐅 
ab \bfG 𝐆 
ab \bfH 𝐇 
ab \bfI 𝐈 
ab \bfJ 𝐉 
ab \bfK 𝐊 
ab \bfL 𝐋 
ab \bfM 𝐌 
ab \bfN 𝐍 
ab \bfO 𝐎 
ab \bfP 𝐏 
ab \bfQ 𝐐 
ab \bfR 𝐑 
ab \bfS 𝐒 
ab \bfT 𝐓 
ab \bfU 𝐔 
ab \bfV 𝐕 
ab \bfW 𝐖 
ab \bfX 𝐗 
ab \bfY 𝐘 
ab \bfZ 𝐙 
ab \bfa 𝐚 
ab \bfb 𝐛 
ab \bfc 𝐜 
ab \bfd 𝐝 
ab \bfe 𝐞 
ab \bff 𝐟 
ab \bfg 𝐠 
ab \bfh 𝐡 
ab \bfi 𝐢 
ab \bfj 𝐣 
ab \bfk 𝐤 
ab \bfl 𝐥 
ab \bfm 𝐦 
ab \bfn 𝐧 
ab \bfo 𝐨 
ab \bfp 𝐩 
ab \bfq 𝐪 
ab \bfr 𝐫 
ab \bfs 𝐬 
ab \bft 𝐭 
ab \bfu 𝐮 
ab \bfv 𝐯 
ab \bfw 𝐰 
ab \bfx 𝐱 
ab \bfy 𝐲 
ab \bfz 𝐳 
ab \itA 𝐴 
ab \itB 𝐵 
ab \itC 𝐶 
ab \itD 𝐷 
ab \itE 𝐸 
ab \itF 𝐹 
ab \itG 𝐺 
ab \itH 𝐻 
ab \itI 𝐼 
ab \itJ 𝐽 
ab \itK 𝐾 
ab \itL 𝐿 
ab \itM 𝑀 
ab \itN 𝑁 
ab \itO 𝑂 
ab \itP 𝑃 
ab \itQ 𝑄 
ab \itR 𝑅 
ab \itS 𝑆 
ab \itT 𝑇 
ab \itU 𝑈 
ab \itV 𝑉 
ab \itW 𝑊 
ab \itX 𝑋 
ab \itY 𝑌 
ab \itZ 𝑍 
ab \ita 𝑎 
ab \itb 𝑏 
ab \itc 𝑐 
ab \itd 𝑑 
ab \ite 𝑒 
ab \itf 𝑓 
ab \itg 𝑔 
ab \iti 𝑖 
ab \itj 𝑗 
ab \itk 𝑘 
ab \itl 𝑙 
ab \itm 𝑚 
ab \itn 𝑛 
ab \ito 𝑜 
ab \itp 𝑝 
ab \itq 𝑞 
ab \itr 𝑟 
ab \its 𝑠 
ab \itt 𝑡 
ab \itu 𝑢 
ab \itv 𝑣 
ab \itw 𝑤 
ab \itx 𝑥 
ab \ity 𝑦 
ab \itz 𝑧 
ab \biA 𝑨 
ab \biB 𝑩 
ab \biC 𝑪 
ab \biD 𝑫 
ab \biE 𝑬 
ab \biF 𝑭 
ab \biG 𝑮 
ab \biH 𝑯 
ab \biI 𝑰 
ab \biJ 𝑱 
ab \biK 𝑲 
ab \biL 𝑳 
ab \biM 𝑴 
ab \biN 𝑵 
ab \biO 𝑶 
ab \biP 𝑷 
ab \biQ 𝑸 
ab \biR 𝑹 
ab \biS 𝑺 
ab \biT 𝑻 
ab \biU 𝑼 
ab \biV 𝑽 
ab \biW 𝑾 
ab \biX 𝑿 
ab \biY 𝒀 
ab \biZ 𝒁 
ab \bia 𝒂 
ab \bib 𝒃 
ab \bic 𝒄 
ab \bid 𝒅 
ab \bie 𝒆 
ab \bif 𝒇 
ab \big 𝒈 
ab \bih 𝒉 
ab \bii 𝒊 
ab \bij 𝒋 
ab \bik 𝒌 
ab \bil 𝒍 
ab \bim 𝒎 
ab \bin 𝒏 
ab \bio 𝒐 
ab \bip 𝒑 
ab \biq 𝒒 
ab \bir 𝒓 
ab \bis 𝒔 
ab \bit 𝒕 
ab \biu 𝒖 
ab \biv 𝒗 
ab \biw 𝒘 
ab \bix 𝒙 
ab \biy 𝒚 
ab \biz 𝒛 
ab \scrA 𝒜 
ab \scrC 𝒞 
ab \scrD 𝒟 
ab \scrG 𝒢 
ab \scrJ 𝒥 
ab \scrK 𝒦 
ab \scrN 𝒩 
ab \scrO 𝒪 
ab \scrP 𝒫 
ab \scrQ 𝒬 
ab \scrS 𝒮 
ab \scrT 𝒯 
ab \scrU 𝒰 
ab \scrV 𝒱 
ab \scrW 𝒲 
ab \scrX 𝒳 
ab \scrY 𝒴 
ab \scrZ 𝒵 
ab \scra 𝒶 
ab \scrb 𝒷 
ab \scrc 𝒸 
ab \scrd 𝒹 
ab \scrf 𝒻 
ab \scrh 𝒽 
ab \scri 𝒾 
ab \scrj 𝒿 
ab \scrk 𝓀 
ab \scrl 𝓁 
ab \scrm 𝓂 
ab \scrn 𝓃 
ab \scrp 𝓅 
ab \scrq 𝓆 
ab \scrr 𝓇 
ab \scrs 𝓈 
ab \scrt 𝓉 
ab \scru 𝓊 
ab \scrv 𝓋 
ab \scrw 𝓌 
ab \scrx 𝓍 
ab \scry 𝓎 
ab \scrz 𝓏 
ab \bscrA 𝓐 
ab \bscrB 𝓑 
ab \bscrC 𝓒 
ab \bscrD 𝓓 
ab \bscrE 𝓔 
ab \bscrF 𝓕 
ab \bscrG 𝓖 
ab \bscrH 𝓗 
ab \bscrI 𝓘 
ab \bscrJ 𝓙 
ab \bscrK 𝓚 
ab \bscrL 𝓛 
ab \bscrM 𝓜 
ab \bscrN 𝓝 
ab \bscrO 𝓞 
ab \bscrP 𝓟 
ab \bscrQ 𝓠 
ab \bscrR 𝓡 
ab \bscrS 𝓢 
ab \bscrT 𝓣 
ab \bscrU 𝓤 
ab \bscrV 𝓥 
ab \bscrW 𝓦 
ab \bscrX 𝓧 
ab \bscrY 𝓨 
ab \bscrZ 𝓩 
ab \bscra 𝓪 
ab \bscrb 𝓫 
ab \bscrc 𝓬 
ab \bscrd 𝓭 
ab \bscre 𝓮 
ab \bscrf 𝓯 
ab \bscrg 𝓰 
ab \bscrh 𝓱 
ab \bscri 𝓲 
ab \bscrj 𝓳 
ab \bscrk 𝓴 
ab \bscrl 𝓵 
ab \bscrm 𝓶 
ab \bscrn 𝓷 
ab \bscro 𝓸 
ab \bscrp 𝓹 
ab \bscrq 𝓺 
ab \bscrr 𝓻 
ab \bscrs 𝓼 
ab \bscrt 𝓽 
ab \bscru 𝓾 
ab \bscrv 𝓿 
ab \bscrw 𝔀 
ab \bscrx 𝔁 
ab \bscry 𝔂 
ab \bscrz 𝔃 
ab \frakA 𝔄 
ab \frakB 𝔅 
ab \frakD 𝔇 
ab \frakE 𝔈 
ab \frakF 𝔉 
ab \frakG 𝔊 
ab \frakJ 𝔍 
ab \frakK 𝔎 
ab \frakL 𝔏 
ab \frakM 𝔐 
ab \frakN 𝔑 
ab \frakO 𝔒 
ab \frakP 𝔓 
ab \frakQ 𝔔 
ab \frakS 𝔖 
ab \frakT 𝔗 
ab \frakU 𝔘 
ab \frakV 𝔙 
ab \frakW 𝔚 
ab \frakX 𝔛 
ab \frakY 𝔜 
ab \fraka 𝔞 
ab \frakb 𝔟 
ab \frakc 𝔠 
ab \frakd 𝔡 
ab \frake 𝔢 
ab \frakf 𝔣 
ab \frakg 𝔤 
ab \frakh 𝔥 
ab \fraki 𝔦 
ab \frakj 𝔧 
ab \frakk 𝔨 
ab \frakl 𝔩 
ab \frakm 𝔪 
ab \frakn 𝔫 
ab \frako 𝔬 
ab \frakp 𝔭 
ab \frakq 𝔮 
ab \frakr 𝔯 
ab \fraks 𝔰 
ab \frakt 𝔱 
ab \fraku 𝔲 
ab \frakv 𝔳 
ab \frakw 𝔴 
ab \frakx 𝔵 
ab \fraky 𝔶 
ab \frakz 𝔷 
ab \bbA 𝔸 
ab \bbB 𝔹 
ab \bbD 𝔻 
ab \bbE 𝔼 
ab \bbF 𝔽 
ab \bbG 𝔾 
ab \bbI 𝕀 
ab \bbJ 𝕁 
ab \bbK 𝕂 
ab \bbL 𝕃 
ab \bbM 𝕄 
ab \bbO 𝕆 
ab \bbS 𝕊 
ab \bbT 𝕋 
ab \bbU 𝕌 
ab \bbV 𝕍 
ab \bbW 𝕎 
ab \bbX 𝕏 
ab \bbY 𝕐 
ab \bba 𝕒 
ab \bbb 𝕓 
ab \bbc 𝕔 
ab \bbd 𝕕 
ab \bbe 𝕖 
ab \bbf 𝕗 
ab \bbg 𝕘 
ab \bbh 𝕙 
ab \bbi 𝕚 
ab \bbj 𝕛 
ab \bbk 𝕜 
ab \bbl 𝕝 
ab \bbm 𝕞 
ab \bbn 𝕟 
ab \bbo 𝕠 
ab \bbp 𝕡 
ab \bbq 𝕢 
ab \bbr 𝕣 
ab \bbs 𝕤 
ab \bbt 𝕥 
ab \bbu 𝕦 
ab \bbv 𝕧 
ab \bbw 𝕨 
ab \bbx 𝕩 
ab \bby 𝕪 
ab \bbz 𝕫 
ab \bfrakA 𝕬 
ab \bfrakB 𝕭 
ab \bfrakC 𝕮 
ab \bfrakD 𝕯 
ab \bfrakE 𝕰 
ab \bfrakF 𝕱 
ab \bfrakG 𝕲 
ab \bfrakH 𝕳 
ab \bfrakI 𝕴 
ab \bfrakJ 𝕵 
ab \bfrakK 𝕶 
ab \bfrakL 𝕷 
ab \bfrakM 𝕸 
ab \bfrakN 𝕹 
ab \bfrakO 𝕺 
ab \bfrakP 𝕻 
ab \bfrakQ 𝕼 
ab \bfrakR 𝕽 
ab \bfrakS 𝕾 
ab \bfrakT 𝕿 
ab \bfrakU 𝖀 
ab \bfrakV 𝖁 
ab \bfrakW 𝖂 
ab \bfrakX 𝖃 
ab \bfrakY 𝖄 
ab \bfrakZ 𝖅 
ab \bfraka 𝖆 
ab \bfrakb 𝖇 
ab \bfrakc 𝖈 
ab \bfrakd 𝖉 
ab \bfrake 𝖊 
ab \bfrakf 𝖋 
ab \bfrakg 𝖌 
ab \bfrakh 𝖍 
ab \bfraki 𝖎 
ab \bfrakj 𝖏 
ab \bfrakk 𝖐 
ab \bfrakl 𝖑 
ab \bfrakm 𝖒 
ab \bfrakn 𝖓 
ab \bfrako 𝖔 
ab \bfrakp 𝖕 
ab \bfrakq 𝖖 
ab \bfrakr 𝖗 
ab \bfraks 𝖘 
ab \bfrakt 𝖙 
ab \bfraku 𝖚 
ab \bfrakv 𝖛 
ab \bfrakw 𝖜 
ab \bfrakx 𝖝 
ab \bfraky 𝖞 
ab \bfrakz 𝖟 
ab \sansA 𝖠 
ab \sansB 𝖡 
ab \sansC 𝖢 
ab \sansD 𝖣 
ab \sansE 𝖤 
ab \sansF 𝖥 
ab \sansG 𝖦 
ab \sansH 𝖧 
ab \sansI 𝖨 
ab \sansJ 𝖩 
ab \sansK 𝖪 
ab \sansL 𝖫 
ab \sansM 𝖬 
ab \sansN 𝖭 
ab \sansO 𝖮 
ab \sansP 𝖯 
ab \sansQ 𝖰 
ab \sansR 𝖱 
ab \sansS 𝖲 
ab \sansT 𝖳 
ab \sansU 𝖴 
ab \sansV 𝖵 
ab \sansW 𝖶 
ab \sansX 𝖷 
ab \sansY 𝖸 
ab \sansZ 𝖹 
ab \sansa 𝖺 
ab \sansb 𝖻 
ab \sansc 𝖼 
ab \sansd 𝖽 
ab \sanse 𝖾 
ab \sansf 𝖿 
ab \sansg 𝗀 
ab \sansh 𝗁 
ab \sansi 𝗂 
ab \sansj 𝗃 
ab \sansk 𝗄 
ab \sansl 𝗅 
ab \sansm 𝗆 
ab \sansn 𝗇 
ab \sanso 𝗈 
ab \sansp 𝗉 
ab \sansq 𝗊 
ab \sansr 𝗋 
ab \sanss 𝗌 
ab \sanst 𝗍 
ab \sansu 𝗎 
ab \sansv 𝗏 
ab \sansw 𝗐 
ab \sansx 𝗑 
ab \sansy 𝗒 
ab \sansz 𝗓 
ab \bsansA 𝗔 
ab \bsansB 𝗕 
ab \bsansC 𝗖 
ab \bsansD 𝗗 
ab \bsansE 𝗘 
ab \bsansF 𝗙 
ab \bsansG 𝗚 
ab \bsansH 𝗛 
ab \bsansI 𝗜 
ab \bsansJ 𝗝 
ab \bsansK 𝗞 
ab \bsansL 𝗟 
ab \bsansM 𝗠 
ab \bsansN 𝗡 
ab \bsansO 𝗢 
ab \bsansP 𝗣 
ab \bsansQ 𝗤 
ab \bsansR 𝗥 
ab \bsansS 𝗦 
ab \bsansT 𝗧 
ab \bsansU 𝗨 
ab \bsansV 𝗩 
ab \bsansW 𝗪 
ab \bsansX 𝗫 
ab \bsansY 𝗬 
ab \bsansZ 𝗭 
ab \bsansa 𝗮 
ab \bsansb 𝗯 
ab \bsansc 𝗰 
ab \bsansd 𝗱 
ab \bsanse 𝗲 
ab \bsansf 𝗳 
ab \bsansg 𝗴 
ab \bsansh 𝗵 
ab \bsansi 𝗶 
ab \bsansj 𝗷 
ab \bsansk 𝗸 
ab \bsansl 𝗹 
ab \bsansm 𝗺 
ab \bsansn 𝗻 
ab \bsanso 𝗼 
ab \bsansp 𝗽 
ab \bsansq 𝗾 
ab \bsansr 𝗿 
ab \bsanss 𝘀 
ab \bsanst 𝘁 
ab \bsansu 𝘂 
ab \bsansv 𝘃 
ab \bsansw 𝘄 
ab \bsansx 𝘅 
ab \bsansy 𝘆 
ab \bsansz 𝘇 
ab \isansA 𝘈 
ab \isansB 𝘉 
ab \isansC 𝘊 
ab \isansD 𝘋 
ab \isansE 𝘌 
ab \isansF 𝘍 
ab \isansG 𝘎 
ab \isansH 𝘏 
ab \isansI 𝘐 
ab \isansJ 𝘑 
ab \isansK 𝘒 
ab \isansL 𝘓 
ab \isansM 𝘔 
ab \isansN 𝘕 
ab \isansO 𝘖 
ab \isansP 𝘗 
ab \isansQ 𝘘 
ab \isansR 𝘙 
ab \isansS 𝘚 
ab \isansT 𝘛 
ab \isansU 𝘜 
ab \isansV 𝘝 
ab \isansW 𝘞 
ab \isansX 𝘟 
ab \isansY 𝘠 
ab \isansZ 𝘡 
ab \isansa 𝘢 
ab \isansb 𝘣 
ab \isansc 𝘤 
ab \isansd 𝘥 
ab \isanse 𝘦 
ab \isansf 𝘧 
ab \isansg 𝘨 
ab \isansh 𝘩 
ab \isansi 𝘪 
ab \isansj 𝘫 
ab \isansk 𝘬 
ab \isansl 𝘭 
ab \isansm 𝘮 
ab \isansn 𝘯 
ab \isanso 𝘰 
ab \isansp 𝘱 
ab \isansq 𝘲 
ab \isansr 𝘳 
ab \isanss 𝘴 
ab \isanst 𝘵 
ab \isansu 𝘶 
ab \isansv 𝘷 
ab \isansw 𝘸 
ab \isansx 𝘹 
ab \isansy 𝘺 
ab \isansz 𝘻 
ab \bisansA 𝘼 
ab \bisansB 𝘽 
ab \bisansC 𝘾 
ab \bisansD 𝘿 
ab \bisansE 𝙀 
ab \bisansF 𝙁 
ab \bisansG 𝙂 
ab \bisansH 𝙃 
ab \bisansI 𝙄 
ab \bisansJ 𝙅 
ab \bisansK 𝙆 
ab \bisansL 𝙇 
ab \bisansM 𝙈 
ab \bisansN 𝙉 
ab \bisansO 𝙊 
ab \bisansP 𝙋 
ab \bisansQ 𝙌 
ab \bisansR 𝙍 
ab \bisansS 𝙎 
ab \bisansT 𝙏 
ab \bisansU 𝙐 
ab \bisansV 𝙑 
ab \bisansW 𝙒 
ab \bisansX 𝙓 
ab \bisansY 𝙔 
ab \bisansZ 𝙕 
ab \bisansa 𝙖 
ab \bisansb 𝙗 
ab \bisansc 𝙘 
ab \bisansd 𝙙 
ab \bisanse 𝙚 
ab \bisansf 𝙛 
ab \bisansg 𝙜 
ab \bisansh 𝙝 
ab \bisansi 𝙞 
ab \bisansj 𝙟 
ab \bisansk 𝙠 
ab \bisansl 𝙡 
ab \bisansm 𝙢 
ab \bisansn 𝙣 
ab \bisanso 𝙤 
ab \bisansp 𝙥 
ab \bisansq 𝙦 
ab \bisansr 𝙧 
ab \bisanss 𝙨 
ab \bisanst 𝙩 
ab \bisansu 𝙪 
ab \bisansv 𝙫 
ab \bisansw 𝙬 
ab \bisansx 𝙭 
ab \bisansy 𝙮 
ab \bisansz 𝙯 
ab \ttA 𝙰 
ab \ttB 𝙱 
ab \ttC 𝙲 
ab \ttD 𝙳 
ab \ttE 𝙴 
ab \ttF 𝙵 
ab \ttG 𝙶 
ab \ttH 𝙷 
ab \ttI 𝙸 
ab \ttJ 𝙹 
ab \ttK 𝙺 
ab \ttL 𝙻 
ab \ttM 𝙼 
ab \ttN 𝙽 
ab \ttO 𝙾 
ab \ttP 𝙿 
ab \ttQ 𝚀 
ab \ttR 𝚁 
ab \ttS 𝚂 
ab \ttT 𝚃 
ab \ttU 𝚄 
ab \ttV 𝚅 
ab \ttW 𝚆 
ab \ttX 𝚇 
ab \ttY 𝚈 
ab \ttZ 𝚉 
ab \tta 𝚊 
ab \ttb 𝚋 
ab \ttc 𝚌 
ab \ttd 𝚍 
ab \tte 𝚎 
ab \ttf 𝚏 
ab \ttg 𝚐 
ab \tth 𝚑 
ab \tti 𝚒 
ab \ttj 𝚓 
ab \ttk 𝚔 
ab \ttl 𝚕 
ab \ttm 𝚖 
ab \ttn 𝚗 
ab \tto 𝚘 
ab \ttp 𝚙 
ab \ttq 𝚚 
ab \ttr 𝚛 
ab \tts 𝚜 
ab \ttt 𝚝 
ab \ttu 𝚞 
ab \ttv 𝚟 
ab \ttw 𝚠 
ab \ttx 𝚡 
ab \tty 𝚢 
ab \ttz 𝚣 
ab \itimath 𝚤 
ab \itjmath 𝚥 
ab \bfAlpha 𝚨 
ab \bfBeta 𝚩 
ab \bfGamma 𝚪 
ab \bfDelta 𝚫 
ab \bfEpsilon 𝚬 
ab \bfZeta 𝚭 
ab \bfEta 𝚮 
ab \bfTheta 𝚯 
ab \bfIota 𝚰 
ab \bfKappa 𝚱 
ab \bfLambda 𝚲 
ab \bfMu 𝚳 
ab \bfNu 𝚴 
ab \bfXi 𝚵 
ab \bfOmicron 𝚶 
ab \bfPi 𝚷 
ab \bfRho 𝚸 
ab \bfvarTheta 𝚹 
ab \bfSigma 𝚺 
ab \bfTau 𝚻 
ab \bfUpsilon 𝚼 
ab \bfPhi 𝚽 
ab \bfChi 𝚾 
ab \bfPsi 𝚿 
ab \bfOmega 𝛀 
ab \bfnabla 𝛁 
ab \bfalpha 𝛂 
ab \bfbeta 𝛃 
ab \bfgamma 𝛄 
ab \bfdelta 𝛅 
ab \bfepsilon 𝛆 
ab \bfzeta 𝛇 
ab \bfeta 𝛈 
ab \bftheta 𝛉 
ab \bfiota 𝛊 
ab \bfkappa 𝛋 
ab \bflambda 𝛌 
ab \bfmu 𝛍 
ab \bfnu 𝛎 
ab \bfxi 𝛏 
ab \bfomicron 𝛐 
ab \bfpi 𝛑 
ab \bfrho 𝛒 
ab \bfvarsigma 𝛓 
ab \bfsigma 𝛔 
ab \bftau 𝛕 
ab \bfupsilon 𝛖 
ab \bfvarphi 𝛗 
ab \bfchi 𝛘 
ab \bfpsi 𝛙 
ab \bfomega 𝛚 
ab \bfpartial 𝛛 
ab \bfvarepsilon 𝛜 
ab \bfvartheta 𝛝 
ab \bfvarkappa 𝛞 
ab \bfphi 𝛟 
ab \bfvarrho 𝛠 
ab \bfvarpi 𝛡 
ab \itAlpha 𝛢 
ab \itBeta 𝛣 
ab \itGamma 𝛤 
ab \itDelta 𝛥 
ab \itEpsilon 𝛦 
ab \itZeta 𝛧 
ab \itEta 𝛨 
ab \itTheta 𝛩 
ab \itIota 𝛪 
ab \itKappa 𝛫 
ab \itLambda 𝛬 
ab \itMu 𝛭 
ab \itNu 𝛮 
ab \itXi 𝛯 
ab \itOmicron 𝛰 
ab \itPi 𝛱 
ab \itRho 𝛲 
ab \itvarTheta 𝛳 
ab \itSigma 𝛴 
ab \itTau 𝛵 
ab \itUpsilon 𝛶 
ab \itPhi 𝛷 
ab \itChi 𝛸 
ab \itPsi 𝛹 
ab \itOmega 𝛺 
ab \itnabla 𝛻 
ab \italpha 𝛼 
ab \itbeta 𝛽 
ab \itgamma 𝛾 
ab \itdelta 𝛿 
ab \itepsilon 𝜀 
ab \itzeta 𝜁 
ab \iteta 𝜂 
ab \ittheta 𝜃 
ab \itiota 𝜄 
ab \itkappa 𝜅 
ab \itlambda 𝜆 
ab \itmu 𝜇 
ab \itnu 𝜈 
ab \itxi 𝜉 
ab \itomicron 𝜊 
ab \itpi 𝜋 
ab \itrho 𝜌 
ab \itvarsigma 𝜍 
ab \itsigma 𝜎 
ab \ittau 𝜏 
ab \itupsilon 𝜐 
ab \itphi 𝜑 
ab \itchi 𝜒 
ab \itpsi 𝜓 
ab \itomega 𝜔 
ab \itpartial 𝜕 
ab \itvarepsilon 𝜖 
ab \itvartheta 𝜗 
ab \itvarkappa 𝜘 
ab \itvarphi 𝜙 
ab \itvarrho 𝜚 
ab \itvarpi 𝜛 
ab \biAlpha 𝜜 
ab \biBeta 𝜝 
ab \biGamma 𝜞 
ab \biDelta 𝜟 
ab \biEpsilon 𝜠 
ab \biZeta 𝜡 
ab \biEta 𝜢 
ab \biTheta 𝜣 
ab \biIota 𝜤 
ab \biKappa 𝜥 
ab \biLambda 𝜦 
ab \biMu 𝜧 
ab \biNu 𝜨 
ab \biXi 𝜩 
ab \biOmicron 𝜪 
ab \biPi 𝜫 
ab \biRho 𝜬 
ab \bivarTheta 𝜭 
ab \biSigma 𝜮 
ab \biTau 𝜯 
ab \biUpsilon 𝜰 
ab \biPhi 𝜱 
ab \biChi 𝜲 
ab \biPsi 𝜳 
ab \biOmega 𝜴 
ab \binabla 𝜵 
ab \bialpha 𝜶 
ab \bibeta 𝜷 
ab \bigamma 𝜸 
ab \bidelta 𝜹 
ab \biepsilon 𝜺 
ab \bizeta 𝜻 
ab \bieta 𝜼 
ab \bitheta 𝜽 
ab \biiota 𝜾 
ab \bikappa 𝜿 
ab \bilambda 𝝀 
ab \bimu 𝝁 
ab \binu 𝝂 
ab \bixi 𝝃 
ab \biomicron 𝝄 
ab \bipi 𝝅 
ab \birho 𝝆 
ab \bivarsigma 𝝇 
ab \bisigma 𝝈 
ab \bitau 𝝉 
ab \biupsilon 𝝊 
ab \biphi 𝝋 
ab \bichi 𝝌 
ab \bipsi 𝝍 
ab \biomega 𝝎 
ab \bipartial 𝝏 
ab \bivarepsilon 𝝐 
ab \bivartheta 𝝑 
ab \bivarkappa 𝝒 
ab \bivarphi 𝝓 
ab \bivarrho 𝝔 
ab \bivarpi 𝝕 
ab \bsansAlpha 𝝖 
ab \bsansBeta 𝝗 
ab \bsansGamma 𝝘 
ab \bsansDelta 𝝙 
ab \bsansEpsilon 𝝚 
ab \bsansZeta 𝝛 
ab \bsansEta 𝝜 
ab \bsansTheta 𝝝 
ab \bsansIota 𝝞 
ab \bsansKappa 𝝟 
ab \bsansLambda 𝝠 
ab \bsansMu 𝝡 
ab \bsansNu 𝝢 
ab \bsansXi 𝝣 
ab \bsansOmicron 𝝤 
ab \bsansPi 𝝥 
ab \bsansRho 𝝦 
ab \bsansvarTheta 𝝧 
ab \bsansSigma 𝝨 
ab \bsansTau 𝝩 
ab \bsansUpsilon 𝝪 
ab \bsansPhi 𝝫 
ab \bsansChi 𝝬 
ab \bsansPsi 𝝭 
ab \bsansOmega 𝝮 
ab \bsansnabla 𝝯 
ab \bsansalpha 𝝰 
ab \bsansbeta 𝝱 
ab \bsansgamma 𝝲 
ab \bsansdelta 𝝳 
ab \bsansepsilon 𝝴 
ab \bsanszeta 𝝵 
ab \bsanseta 𝝶 
ab \bsanstheta 𝝷 
ab \bsansiota 𝝸 
ab \bsanskappa 𝝹 
ab \bsanslambda 𝝺 
ab \bsansmu 𝝻 
ab \bsansnu 𝝼 
ab \bsansxi 𝝽 
ab \bsansomicron 𝝾 
ab \bsanspi 𝝿 
ab \bsansrho 𝞀 
ab \bsansvarsigma 𝞁 
ab \bsanssigma 𝞂 
ab \bsanstau 𝞃 
ab \bsansupsilon 𝞄 
ab \bsansphi 𝞅 
ab \bsanschi 𝞆 
ab \bsanspsi 𝞇 
ab \bsansomega 𝞈 
ab \bsanspartial 𝞉 
ab \bsansvarepsilon 𝞊 
ab \bsansvartheta 𝞋 
ab \bsansvarkappa 𝞌 
ab \bsansvarphi 𝞍 
ab \bsansvarrho 𝞎 
ab \bsansvarpi 𝞏 
ab \bisansAlpha 𝞐 
ab \bisansBeta 𝞑 
ab \bisansGamma 𝞒 
ab \bisansDelta 𝞓 
ab \bisansEpsilon 𝞔 
ab \bisansZeta 𝞕 
ab \bisansEta 𝞖 
ab \bisansTheta 𝞗 
ab \bisansIota 𝞘 
ab \bisansKappa 𝞙 
ab \bisansLambda 𝞚 
ab \bisansMu 𝞛 
ab \bisansNu 𝞜 
ab \bisansXi 𝞝 
ab \bisansOmicron 𝞞 
ab \bisansPi 𝞟 
ab \bisansRho 𝞠 
ab \bisansvarTheta 𝞡 
ab \bisansSigma 𝞢 
ab \bisansTau 𝞣 
ab \bisansUpsilon 𝞤 
ab \bisansPhi 𝞥 
ab \bisansChi 𝞦 
ab \bisansPsi 𝞧 
ab \bisansOmega 𝞨 
ab \bisansnabla 𝞩 
ab \bisansalpha 𝞪 
ab \bisansbeta 𝞫 
ab \bisansgamma 𝞬 
ab \bisansdelta 𝞭 
ab \bisansepsilon 𝞮 
ab \bisanszeta 𝞯 
ab \bisanseta 𝞰 
ab \bisanstheta 𝞱 
ab \bisansiota 𝞲 
ab \bisanskappa 𝞳 
ab \bisanslambda 𝞴 
ab \bisansmu 𝞵 
ab \bisansnu 𝞶 
ab \bisansxi 𝞷 
ab \bisansomicron 𝞸 
ab \bisanspi 𝞹 
ab \bisansrho 𝞺 
ab \bisansvarsigma 𝞻 
ab \bisanssigma 𝞼 
ab \bisanstau 𝞽 
ab \bisansupsilon 𝞾 
ab \bisansphi 𝞿 
ab \bisanschi 𝟀 
ab \bisanspsi 𝟁 
ab \bisansomega 𝟂 
ab \bisanspartial 𝟃 
ab \bisansvarepsilon 𝟄 
ab \bisansvartheta 𝟅 
ab \bisansvarkappa 𝟆 
ab \bisansvarphi 𝟇 
ab \bisansvarrho 𝟈 
ab \bisansvarpi 𝟉 
ab \bfDigamma 𝟊 
ab \bfdigamma 𝟋 
ab \bfzero 𝟎 
ab \bfone 𝟏 
ab \bftwo 𝟐 
ab \bfthree 𝟑 
ab \bffour 𝟒 
ab \bffive 𝟓 
ab \bfsix 𝟔 
ab \bfseven 𝟕 
ab \bfeight 𝟖 
ab \bfnine 𝟗 
ab \bbzero 𝟘 
ab \bbone 𝟙 
ab \bbtwo 𝟚 
ab \bbthree 𝟛 
ab \bbfour 𝟜 
ab \bbfive 𝟝 
ab \bbsix 𝟞 
ab \bbseven 𝟟 
ab \bbeight 𝟠 
ab \bbnine 𝟡 
ab \sanszero 𝟢 
ab \sansone 𝟣 
ab \sanstwo 𝟤 
ab \sansthree 𝟥 
ab \sansfour 𝟦 
ab \sansfive 𝟧 
ab \sanssix 𝟨 
ab \sansseven 𝟩 
ab \sanseight 𝟪 
ab \sansnine 𝟫 
ab \bsanszero 𝟬 
ab \bsansone 𝟭 
ab \bsanstwo 𝟮 
ab \bsansthree 𝟯 
ab \bsansfour 𝟰 
ab \bsansfive 𝟱 
ab \bsanssix 𝟲 
ab \bsansseven 𝟳 
ab \bsanseight 𝟴 
ab \bsansnine 𝟵 
ab \ttzero 𝟶 
ab \ttone 𝟷 
ab \tttwo 𝟸 
ab \ttthree 𝟹 
ab \ttfour 𝟺 
ab \ttfive 𝟻 
ab \ttsix 𝟼 
ab \ttseven 𝟽 
ab \tteight 𝟾 
ab \ttnine 𝟿 
ab \mahjong 🀄 
ab \black_joker 🃏 
ab \a 🅰 
ab \b 🅱 
ab \o2 🅾 
ab \parking 🅿 
ab \ab 🆎 
ab \cl 🆑 
ab \cool 🆒 
ab \free 🆓 
ab \id 🆔 
ab \new 🆕 
ab \ng 🆖 
ab \ok 🆗 
ab \sos 🆘 
ab \up 🆙 
ab \vs 🆚 
ab \koko 🈁 
ab \sa 🈂 
ab \u7121 🈚 
ab \u6307 🈯 
ab \u7981 🈲 
ab \u7a7a 🈳 
ab \u5408 🈴 
ab \u6e80 🈵 
ab \u6709 🈶 
ab \u6708 🈷 
ab \u7533 🈸 
ab \u5272 🈹 
ab \u55b6 🈺 
ab \ideograph_advantage 🉐 
ab \accept 🉑 
ab \cyclone 🌀 
ab \foggy 🌁 
ab \closed_umbrella 🌂 
ab \night_with_stars 🌃 
ab \sunrise_over_mountains 🌄 
ab \sunrise 🌅 
ab \city_sunset 🌆 
ab \city_sunrise 🌇 
ab \rainbow 🌈 
ab \bridge_at_night 🌉 
ab \ocean 🌊 
ab \volcano 🌋 
ab \milky_way 🌌 
ab \earth_africa 🌍 
ab \earth_americas 🌎 
ab \earth_asia 🌏 
ab \globe_with_meridians 🌐 
ab \new_moon 🌑 
ab \waxing_crescent_moon 🌒 
ab \first_quarter_moon 🌓 
ab \moon 🌔 
ab \full_moon 🌕 
ab \waning_gibbous_moon 🌖 
ab \last_quarter_moon 🌗 
ab \waning_crescent_moon 🌘 
ab \crescent_moon 🌙 
ab \new_moon_with_face 🌚 
ab \first_quarter_moon_with_face 🌛 
ab \last_quarter_moon_with_face 🌜 
ab \full_moon_with_face 🌝 
ab \sun_with_face 🌞 
ab \star2 🌟 
ab \stars 🌠 
ab \chestnut 🌰 
ab \seedling 🌱 
ab \evergreen_tree 🌲 
ab \deciduous_tree 🌳 
ab \palm_tree 🌴 
ab \cactus 🌵 
ab \tulip 🌷 
ab \cherry_blossom 🌸 
ab \rose 🌹 
ab \hibiscus 🌺 
ab \sunflower 🌻 
ab \blossom 🌼 
ab \corn 🌽 
ab \ear_of_rice 🌾 
ab \herb 🌿 
ab \four_leaf_clover 🍀 
ab \maple_leaf 🍁 
ab \fallen_leaf 🍂 
ab \leaves 🍃 
ab \mushroom 🍄 
ab \tomato 🍅 
ab \eggplant 🍆 
ab \grapes 🍇 
ab \melon 🍈 
ab \watermelon 🍉 
ab \tangerine 🍊 
ab \lemon 🍋 
ab \banana 🍌 
ab \pineapple 🍍 
ab \apple 🍎 
ab \green_apple 🍏 
ab \pear 🍐 
ab \peach 🍑 
ab \cherries 🍒 
ab \strawberry 🍓 
ab \hamburger 🍔 
ab \pizza 🍕 
ab \meat_on_bone 🍖 
ab \poultry_leg 🍗 
ab \rice_cracker 🍘 
ab \rice_ball 🍙 
ab \rice 🍚 
ab \curry 🍛 
ab \ramen 🍜 
ab \spaghetti 🍝 
ab \bread 🍞 
ab \fries 🍟 
ab \sweet_potato 🍠 
ab \dango 🍡 
ab \oden 🍢 
ab \sushi 🍣 
ab \fried_shrimp 🍤 
ab \fish_cake 🍥 
ab \icecream 🍦 
ab \shaved_ice 🍧 
ab \ice_cream 🍨 
ab \doughnut 🍩 
ab \cookie 🍪 
ab \chocolate_bar 🍫 
ab \candy 🍬 
ab \lollipop 🍭 
ab \custard 🍮 
ab \honey_pot 🍯 
ab \cake 🍰 
ab \bento 🍱 
ab \stew 🍲 
ab \egg 🍳 
ab \fork_and_knife 🍴 
ab \tea 🍵 
ab \sake 🍶 
ab \wine_glass 🍷 
ab \cocktail 🍸 
ab \tropical_drink 🍹 
ab \beer 🍺 
ab \beers 🍻 
ab \baby_bottle 🍼 
ab \ribbon 🎀 
ab \gift 🎁 
ab \birthday 🎂 
ab \jack_o_lantern 🎃 
ab \christmas_tree 🎄 
ab \santa 🎅 
ab \fireworks 🎆 
ab \sparkler 🎇 
ab \balloon 🎈 
ab \tada 🎉 
ab \confetti_ball 🎊 
ab \tanabata_tree 🎋 
ab \crossed_flags 🎌 
ab \bamboo 🎍 
ab \dolls 🎎 
ab \flags 🎏 
ab \wind_chime 🎐 
ab \rice_scene 🎑 
ab \school_satchel 🎒 
ab \mortar_board 🎓 
ab \carousel_horse 🎠 
ab \ferris_wheel 🎡 
ab \roller_coaster 🎢 
ab \fishing_pole_and_fish 🎣 
ab \microphone 🎤 
ab \movie_camera 🎥 
ab \cinema 🎦 
ab \headphones 🎧 
ab \art 🎨 
ab \tophat 🎩 
ab \circus_tent 🎪 
ab \ticket 🎫 
ab \clapper 🎬 
ab \performing_arts 🎭 
ab \video_game 🎮 
ab \dart 🎯 
ab \slot_machine 🎰 
ab \8ball 🎱 
ab \game_die 🎲 
ab \bowling 🎳 
ab \flower_playing_cards 🎴 
ab \musical_note 🎵 
ab \notes 🎶 
ab \saxophone 🎷 
ab \guitar 🎸 
ab \musical_keyboard 🎹 
ab \trumpet 🎺 
ab \violin 🎻 
ab \musical_score 🎼 
ab \running_shirt_with_sash 🎽 
ab \tennis 🎾 
ab \ski 🎿 
ab \basketball 🏀 
ab \checkered_flag 🏁 
ab \snowboarder 🏂 
ab \runner 🏃 
ab \surfer 🏄 
ab \trophy 🏆 
ab \horse_racing 🏇 
ab \football 🏈 
ab \rugby_football 🏉 
ab \swimmer 🏊 
ab \house 🏠 
ab \house_with_garden 🏡 
ab \office 🏢 
ab \post_office 🏣 
ab \european_post_office 🏤 
ab \hospital 🏥 
ab \bank 🏦 
ab \atm 🏧 
ab \hotel 🏨 
ab \love_hotel 🏩 
ab \convenience_store 🏪 
ab \school 🏫 
ab \department_store 🏬 
ab \factory 🏭 
ab \izakaya_lantern 🏮 
ab \japanese_castle 🏯 
ab \european_castle 🏰 
ab \skin-tone-2 🏻 
ab \skin-tone-3 🏼 
ab \skin-tone-4 🏽 
ab \skin-tone-5 🏾 
ab \skin-tone-6 🏿 
ab \rat 🐀 
ab \mouse2 🐁 
ab \ox 🐂 
ab \water_buffalo 🐃 
ab \cow2 🐄 
ab \tiger2 🐅 
ab \leopard 🐆 
ab \rabbit2 🐇 
ab \cat2 🐈 
ab \dragon 🐉 
ab \crocodile 🐊 
ab \whale2 🐋 
ab \snail 🐌 
ab \snake 🐍 
ab \racehorse 🐎 
ab \ram 🐏 
ab \goat 🐐 
ab \sheep 🐑 
ab \monkey 🐒 
ab \rooster 🐓 
ab \chicken 🐔 
ab \dog2 🐕 
ab \pig2 🐖 
ab \boar 🐗 
ab \elephant 🐘 
ab \octopus 🐙 
ab \shell 🐚 
ab \bug 🐛 
ab \ant 🐜 
ab \bee 🐝 
ab \beetle 🐞 
ab \fish 🐟 
ab \tropical_fish 🐠 
ab \blowfish 🐡 
ab \turtle 🐢 
ab \hatching_chick 🐣 
ab \baby_chick 🐤 
ab \hatched_chick 🐥 
ab \bird 🐦 
ab \penguin 🐧 
ab \koala 🐨 
ab \poodle 🐩 
ab \dromedary_camel 🐪 
ab \camel 🐫 
ab \dolphin 🐬 
ab \mouse 🐭 
ab \cow 🐮 
ab \tiger 🐯 
ab \rabbit 🐰 
ab \cat 🐱 
ab \dragon_face 🐲 
ab \whale 🐳 
ab \horse 🐴 
ab \monkey_face 🐵 
ab \dog 🐶 
ab \pig 🐷 
ab \frog 🐸 
ab \hamster 🐹 
ab \wolf 🐺 
ab \bear 🐻 
ab \panda_face 🐼 
ab \pig_nose 🐽 
ab \feet 🐾 
ab \eyes 👀 
ab \ear 👂 
ab \nose 👃 
ab \lips 👄 
ab \tongue 👅 
ab \point_up_2 👆 
ab \point_down 👇 
ab \point_left 👈 
ab \point_right 👉 
ab \facepunch 👊 
ab \wave 👋 
ab \ok_hand 👌 
ab \+1 👍 
ab \-1 👎 
ab \clap 👏 
ab \open_hands 👐 
ab \crown 👑 
ab \womans_hat 👒 
ab \eyeglasses 👓 
ab \necktie 👔 
ab \shirt 👕 
ab \jeans 👖 
ab \dress 👗 
ab \kimono 👘 
ab \bikini 👙 
ab \womans_clothes 👚 
ab \purse 👛 
ab \handbag 👜 
ab \pouch 👝 
ab \mans_shoe 👞 
ab \athletic_shoe 👟 
ab \high_heel 👠 
ab \sandal 👡 
ab \boot 👢 
ab \footprints 👣 
ab \bust_in_silhouette 👤 
ab \busts_in_silhouette 👥 
ab \boy 👦 
ab \girl 👧 
ab \man 👨 
ab \woman 👩 
ab \family 👪 
ab \couple 👫 
ab \two_men_holding_hands 👬 
ab \two_women_holding_hands 👭 
ab \cop 👮 
ab \dancers 👯 
ab \bride_with_veil 👰 
ab \person_with_blond_hair 👱 
ab \man_with_gua_pi_mao 👲 
ab \man_with_turban 👳 
ab \older_man 👴 
ab \older_woman 👵 
ab \baby 👶 
ab \construction_worker 👷 
ab \princess 👸 
ab \japanese_ogre 👹 
ab \japanese_goblin 👺 
ab \ghost 👻 
ab \angel 👼 
ab \alien 👽 
ab \space_invader 👾 
ab \imp 👿 
ab \skull 💀 
ab \information_desk_person 💁 
ab \guardsman 💂 
ab \dancer 💃 
ab \lipstick 💄 
ab \nail_care 💅 
ab \massage 💆 
ab \haircut 💇 
ab \barber 💈 
ab \syringe 💉 
ab \pill 💊 
ab \kiss 💋 
ab \love_letter 💌 
ab \ring 💍 
ab \gem 💎 
ab \couplekiss 💏 
ab \bouquet 💐 
ab \couple_with_heart 💑 
ab \wedding 💒 
ab \heartbeat 💓 
ab \broken_heart 💔 
ab \two_hearts 💕 
ab \sparkling_heart 💖 
ab \heartpulse 💗 
ab \cupid 💘 
ab \blue_heart 💙 
ab \green_heart 💚 
ab \yellow_heart 💛 
ab \purple_heart 💜 
ab \gift_heart 💝 
ab \revolving_hearts 💞 
ab \heart_decoration 💟 
ab \diamond_shape_with_a_dot_inside 💠 
ab \bulb 💡 
ab \anger 💢 
ab \bomb 💣 
ab \zzz 💤 
ab \boom 💥 
ab \sweat_drops 💦 
ab \droplet 💧 
ab \dash 💨 
ab \hankey 💩 
ab \muscle 💪 
ab \dizzy 💫 
ab \speech_balloon 💬 
ab \thought_balloon 💭 
ab \white_flower 💮 
ab \100 💯 
ab \moneybag 💰 
ab \currency_exchange 💱 
ab \heavy_dollar_sign 💲 
ab \credit_card 💳 
ab \yen 💴 
ab \dollar 💵 
ab \euro 💶 
ab \pound 💷 
ab \money_with_wings 💸 
ab \chart 💹 
ab \seat 💺 
ab \computer 💻 
ab \briefcase 💼 
ab \minidisc 💽 
ab \floppy_disk 💾 
ab \cd 💿 
ab \dvd 📀 
ab \file_folder 📁 
ab \open_file_folder 📂 
ab \page_with_curl 📃 
ab \page_facing_up 📄 
ab \date 📅 
ab \calendar 📆 
ab \card_index 📇 
ab \chart_with_upwards_trend 📈 
ab \chart_with_downwards_trend 📉 
ab \bar_chart 📊 
ab \clipboard 📋 
ab \pushpin 📌 
ab \round_pushpin 📍 
ab \paperclip 📎 
ab \straight_ruler 📏 
ab \triangular_ruler 📐 
ab \bookmark_tabs 📑 
ab \ledger 📒 
ab \notebook 📓 
ab \notebook_with_decorative_cover 📔 
ab \closed_book 📕 
ab \book 📖 
ab \green_book 📗 
ab \blue_book 📘 
ab \orange_book 📙 
ab \books 📚 
ab \name_badge 📛 
ab \scroll 📜 
ab \memo 📝 
ab \telephone_receiver 📞 
ab \pager 📟 
ab \fax 📠 
ab \satellite 📡 
ab \loudspeaker 📢 
ab \mega 📣 
ab \outbox_tray 📤 
ab \inbox_tray 📥 
ab \package 📦 
ab \e-mail 📧 
ab \incoming_envelope 📨 
ab \envelope_with_arrow 📩 
ab \mailbox_closed 📪 
ab \mailbox 📫 
ab \mailbox_with_mail 📬 
ab \mailbox_with_no_mail 📭 
ab \postbox 📮 
ab \postal_horn 📯 
ab \newspaper 📰 
ab \iphone 📱 
ab \calling 📲 
ab \vibration_mode 📳 
ab \mobile_phone_off 📴 
ab \no_mobile_phones 📵 
ab \signal_strength 📶 
ab \camera 📷 
ab \video_camera 📹 
ab \tv 📺 
ab \radio 📻 
ab \vhs 📼 
ab \twisted_rightwards_arrows 🔀 
ab \repeat 🔁 
ab \repeat_one 🔂 
ab \arrows_clockwise 🔃 
ab \arrows_counterclockwise 🔄 
ab \low_brightness 🔅 
ab \high_brightness 🔆 
ab \mute 🔇 
ab \speaker 🔈 
ab \sound 🔉 
ab \loud_sound 🔊 
ab \battery 🔋 
ab \electric_plug 🔌 
ab \mag 🔍 
ab \mag_right 🔎 
ab \lock_with_ink_pen 🔏 
ab \closed_lock_with_key 🔐 
ab \key 🔑 
ab \lock 🔒 
ab \unlock 🔓 
ab \bell 🔔 
ab \no_bell 🔕 
ab \bookmark 🔖 
ab \link 🔗 
ab \radio_button 🔘 
ab \back 🔙 
ab \end 🔚 
ab \on 🔛 
ab \soon 🔜 
ab \top 🔝 
ab \underage 🔞 
ab \keycap_ten 🔟 
ab \capital_abcd 🔠 
ab \abcd 🔡 
ab \1234 🔢 
ab \symbols 🔣 
ab \abc 🔤 
ab \fire 🔥 
ab \flashlight 🔦 
ab \wrench 🔧 
ab \hammer 🔨 
ab \nut_and_bolt 🔩 
ab \hocho 🔪 
ab \gun 🔫 
ab \microscope 🔬 
ab \telescope 🔭 
ab \crystal_ball 🔮 
ab \six_pointed_star 🔯 
ab \beginner 🔰 
ab \trident 🔱 
ab \black_square_button 🔲 
ab \white_square_button 🔳 
ab \red_circle 🔴 
ab \large_blue_circle 🔵 
ab \large_orange_diamond 🔶 
ab \large_blue_diamond 🔷 
ab \small_orange_diamond 🔸 
ab \small_blue_diamond 🔹 
ab \small_red_triangle 🔺 
ab \small_red_triangle_down 🔻 
ab \arrow_up_small 🔼 
ab \arrow_down_small 🔽 
ab \clock1 🕐 
ab \clock2 🕑 
ab \clock3 🕒 
ab \clock4 🕓 
ab \clock5 🕔 
ab \clock6 🕕 
ab \clock7 🕖 
ab \clock8 🕗 
ab \clock9 🕘 
ab \clock10 🕙 
ab \clock11 🕚 
ab \clock12 🕛 
ab \clock130 🕜 
ab \clock230 🕝 
ab \clock330 🕞 
ab \clock430 🕟 
ab \clock530 🕠 
ab \clock630 🕡 
ab \clock730 🕢 
ab \clock830 🕣 
ab \clock930 🕤 
ab \clock1030 🕥 
ab \clock1130 🕦 
ab \clock1230 🕧 
ab \mount_fuji 🗻 
ab \tokyo_tower 🗼 
ab \statue_of_liberty 🗽 
ab \japan 🗾 
ab \moyai 🗿 
ab \grinning 😀 
ab \grin 😁 
ab \joy 😂 
ab \smiley 😃 
ab \smile 😄 
ab \sweat_smile 😅 
ab \laughing 😆 
ab \innocent 😇 
ab \smiling_imp 😈 
ab \wink 😉 
ab \blush 😊 
ab \yum 😋 
ab \relieved 😌 
ab \heart_eyes 😍 
ab \sunglasses 😎 
ab \smirk 😏 
ab \neutral_face 😐 
ab \expressionless 😑 
ab \unamused 😒 
ab \sweat 😓 
ab \pensive 😔 
ab \confused 😕 
ab \confounded 😖 
ab \kissing 😗 
ab \kissing_heart 😘 
ab \kissing_smiling_eyes 😙 
ab \kissing_closed_eyes 😚 
ab \stuck_out_tongue 😛 
ab \stuck_out_tongue_winking_eye 😜 
ab \stuck_out_tongue_closed_eyes 😝 
ab \disappointed 😞 
ab \worried 😟 
ab \angry 😠 
ab \rage 😡 
ab \cry 😢 
ab \persevere 😣 
ab \triumph 😤 
ab \disappointed_relieved 😥 
ab \frowning 😦 
ab \anguished 😧 
ab \fearful 😨 
ab \weary 😩 
ab \sleepy 😪 
ab \tired_face 😫 
ab \grimacing 😬 
ab \sob 😭 
ab \open_mouth 😮 
ab \hushed 😯 
ab \cold_sweat 😰 
ab \scream 😱 
ab \astonished 😲 
ab \flushed 😳 
ab \sleeping 😴 
ab \dizzy_face 😵 
ab \no_mouth 😶 
ab \mask 😷 
ab \smile_cat 😸 
ab \joy_cat 😹 
ab \smiley_cat 😺 
ab \heart_eyes_cat 😻 
ab \smirk_cat 😼 
ab \kissing_cat 😽 
ab \pouting_cat 😾 
ab \crying_cat_face 😿 
ab \scream_cat 🙀 
ab \no_good 🙅 
ab \ok_woman 🙆 
ab \bow 🙇 
ab \see_no_evil 🙈 
ab \hear_no_evil 🙉 
ab \speak_no_evil 🙊 
ab \raising_hand 🙋 
ab \raised_hands 🙌 
ab \person_frowning 🙍 
ab \person_with_pouting_face 🙎 
ab \pray 🙏 
ab \rocket 🚀 
ab \helicopter 🚁 
ab \steam_locomotive 🚂 
ab \railway_car 🚃 
ab \bullettrain_side 🚄 
ab \bullettrain_front 🚅 
ab \train2 🚆 
ab \metro 🚇 
ab \light_rail 🚈 
ab \station 🚉 
ab \tram 🚊 
ab \train 🚋 
ab \bus 🚌 
ab \oncoming_bus 🚍 
ab \trolleybus 🚎 
ab \busstop 🚏 
ab \minibus 🚐 
ab \ambulance 🚑 
ab \fire_engine 🚒 
ab \police_car 🚓 
ab \oncoming_police_car 🚔 
ab \taxi 🚕 
ab \oncoming_taxi 🚖 
ab \car 🚗 
ab \oncoming_automobile 🚘 
ab \blue_car 🚙 
ab \truck 🚚 
ab \articulated_lorry 🚛 
ab \tractor 🚜 
ab \monorail 🚝 
ab \mountain_railway 🚞 
ab \suspension_railway 🚟 
ab \mountain_cableway 🚠 
ab \aerial_tramway 🚡 
ab \ship 🚢 
ab \rowboat 🚣 
ab \speedboat 🚤 
ab \traffic_light 🚥 
ab \vertical_traffic_light 🚦 
ab \construction 🚧 
ab \rotating_light 🚨 
ab \triangular_flag_on_post 🚩 
ab \door 🚪 
ab \no_entry_sign 🚫 
ab \smoking 🚬 
ab \no_smoking 🚭 
ab \put_litter_in_its_place 🚮 
ab \do_not_litter 🚯 
ab \potable_water 🚰 
ab \non-potable_water 🚱 
ab \bike 🚲 
ab \no_bicycles 🚳 
ab \bicyclist 🚴 
ab \mountain_bicyclist 🚵 
ab \walking 🚶 
ab \no_pedestrians 🚷 
ab \children_crossing 🚸 
ab \mens 🚹 
ab \womens 🚺 
ab \restroom 🚻 
ab \baby_symbol 🚼 
ab \toilet 🚽 
ab \wc 🚾 
ab \shower 🚿 
ab \bath 🛀 
ab \bathtub 🛁 
ab \passport_control 🛂 
ab \customs 🛃 
ab \baggage_claim 🛄 
ab \left_luggage 🛅 
