#! /bin/sh

## AUTOSTART
sxhxd &
~/.config/polybar/launch.sh &
~/scripts/monitors_1080-720.sh &
compton --config ~/.config/compton/compton.conf &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor HDMI1 -d I II III IV
bspc monitor DP1 -d VI VII VIII IX

bspc config border_width         1
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config pointer_modifier shift
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc rule -a Chromium desktop='^2'
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color2"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color1"
# Use the line below if you are on bspwm < 0.9.4
#bspc config presel_border_color "$color1"
